### ISSUE TITLE
Scrolling speed doesn't match finger speed

### ISSUE THREAD

**Issue by xfarrow** [duckduckgo/Android#700] opened 2020-02-03 13:31 UTC
When scrolling a page, the URL menu hides, right? But when it's hiding the scrolling speed changes, leading to an unexpected behaviour.

**Comment by Poopooracoocoo** [comment] 2020-02-05 08:52
Related: #689 

The way DDG implemented the toolbar is like Firefox Focus. We like how Chrome's toolbar works. 

If you swipe on the page, it scrolls both the page and the toolbar. In Chrome the toolbar scrolls away first, then the page (instead of both simultaneously) and also snaps away.

**Comment by cmonfortep** [comment] 2020-02-05 13:55
Thanks for the feedback. I already see @Poopooracoocoo correctly summarized how hiding/showing the toolbar affects the scrolling effect. 

Seems like we have some issues related to our toolbar animations: https://github.com/duckduckgo/Android/issues/638 https://github.com/duckduckgo/Android/issues/689

I will create a task in our internal backlog to keep this improvement under our radar.

**Comment by blackboxlogic** [comment] 2020-09-20 23:25
To add a particularly bad example, go to https://preview.ideditor.com/release on mobile DDG. It is a "slippy" map, where user drags across the screen to pan and zoom. When user drags up (to pan south), the browser's top bar auto-hides, which moves the page under the user's touch point, which the page registers as a quick touch drag, and flings the map _way_ further south.

I think this would be fixed with @Poopooracoocoo description:
> If you swipe on the page, it scrolls both the page and the toolbar. In Chrome the toolbar scrolls away first...

I imagine this as the page and the scrollbar becoming _attached_ to each other for scrolling purposes _while_ the bar is in the process of hiding or showing. If user stops scrolling while the bar is half-shown, then the bar stays half-shown

**Comment by cmonfortep** [comment] 2021-04-08 10:41
Now that we understand more this issues, it's very related to this one https://github.com/duckduckgo/Android/issues/914. 

The problem is again how webview is positioned when the toolbar is visible, and how it reacts to the scroll. Once we fix that issue, this will be solved by the same fix. We can't fix this one without fixing the other one.

Closing this issue as it will be covered by https://github.com/duckduckgo/Android/issues/914

**Closed by cmonfortep** 2021-04-08 10:41 UTC
Labels: enhancement
