### ISSUE TITLE
disconnecting the physical keyboard while a video is playing in fullscreen causes a black-screen

### ISSUE THREAD

**Issue by frknltrk** [duckduckgo/Android#957] opened 2020-10-06 18:33 UTC
**Describe the bug**
during a video playing on the screen in fullscreen, when i disconnect the physical keyboard from the tablet, i see nothing but a pure black-screen (generally video is still playing in background)

**How to Reproduce**
1. Tap on the fullscreen icon of the video player
2. Disconnect the physical keyboard from the tablet
3. Screen goes all black, can't to anything... (and user has to close and restart the app)

**Expected behavior**
Video should be keep playing properly

**Smartphone (please complete the following information):**
 - DDG App Version: 5.65.0
 - Device: Samsung Galaxy s5e
 - OS: LineageOS 17.1 (Android 10)

**Comment by cmonfortep** [comment] 2020-10-15 21:33
Thanks for reporting @furkanunluturkk, however, I don't have a physical keyboard to test this issue on my devices.

I saw you reported another scenario first (I've got an email notification :D ): 

_Steps to reproduce the behavior:
Tap on the fullscreen icon of the video player
Try to rotate the screen or presss the power button of the device
Screen goes all black, can't to anything... (and user has to close and restart the app)_

Is that also happening on your device?

I tried to follow those steps and I was not able to reproduce the issue but got into another one. In my case:

1. Tap on the fullscreen icon of the video player
2. Press the power button of the device (turns off the screen)
3. Turn on the screen again (app is in foreground again)
4. Video is still present
5. Pressing back navigates to a black screen.

Could you tell me if you are having this issue in other scenarios, and not only when disconnecting your physical keyboard?

**Comment by furkanunluturkk** [comment] 2020-10-16 06:47
> Thanks for reporting @furkanunluturkk, however, I don't have a physical keyboard to test this issue on my devices.
> 
> I saw you reported another scenario first (I've got an email notification :D ):
> 
> _Steps to reproduce the behavior: Tap on the fullscreen icon of the video player Try to rotate the screen or presss the power button of the device Screen goes all black, can't to anything... (and user has to close and restart the app)_
> 
> Is that also happening on your device?
> 
> I tried to follow those steps and I was not able to reproduce the issue but got into another one. In my case:
> 
>     1. Tap on the fullscreen icon of the video player
> 
>     2. Press the power button of the device (turns off the screen)
> 
>     3. Turn on the screen again (app is in foreground again)
> 
>     4. Video is still present
> 
>     5. Pressing back navigates to a black screen.
> 
> 
> Could you tell me if you are having this issue in other scenarios, and not only when disconnecting your physical keyboard?

Oh, no. First one was sort of a mistake, that's why i had modified later. It only happens when I connect/disconnect my s5e physical keyboard.
And one thing to note that: It actually reloads/refreshes the page when i connect/disconnect my keyboard. Maybe that's the reason of the black-screen. App tries to reload the page when a media playing full-screen thus it crashes.

**Comment by cmonfortep** [comment] 2020-10-16 07:45
Thanks for the response. I assume that the screen goes black and sound also stops, could you confirm that?

And just to check if the issue I found can be also related, what happens if you press back on that screen? does it navigate back to the browser or stays in that black screen?

**Comment by furkanunluturkk** [comment] 2020-10-16 09:06
> Thanks for the response. I assume that the screen goes black and sound also stops, could you confirm that?
> 
> And just to check if the issue I found can be also related, what happens if you press back on that screen? does it navigate back to the browser or stays in that black screen?

No no, audio doesn't stop but only the video. Here I captured a record of the procedure:

**Comment by cmonfortep** [comment] 2020-10-20 09:40
Thanks.

Ok, so to summarize all the info, this is what happens:
1. Open video in full screen mode
1. Disconnect physical keyboard
1. Screen goes black, but audio doesn't stop playing
1. Pressing back does nothing

**Comment by furkanunluturkk** [comment] 2020-10-20 10:51
> Thanks.
> 
> Ok, so to summarize all the info, this is what happens:
> 
> 1. Open video in full screen mode
> 2. Disconnect physical keyboard
> 3. Screen goes black, but audio doesn't stop playing
> 4. Pressing back does nothing

Exactly.

**Comment by cmonfortep** [comment] 2020-12-15 14:15
Sadly, I've not been able to reproduce this issue in my test devices and we haven't received similar reports.

I will close this issue as not further exploration can be made. Thanks.

**Closed by cmonfortep** 2020-12-15 14:15 UTC
Labels: bug, needs triage
