### ISSUE TITLE
DuckduckGo browser for linux systems

### ISSUE THREAD

**Issue by rafnov** [duckduckgo/Android#5133] opened 2024-10-13 07:02 UTC
### Describe the bug

No Duckduck go for linux on app page

### How to Reproduce

Go to https://duckduckgo.com/app and search download for Linux

### Expected behavior

Existing Linux version

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by marcosholgado** [comment] 2024-10-13 11:18
Not a bug related to our Android browser, closing.

**Closed by marcosholgado** 2024-10-13 11:18 UTC
Labels: bug, needs triage

**Comment by rafnov** [comment] 2024-10-13 11:22
Sorry, Marcos, I'm writing from Android app and ot seems limited capabilities. Besides I am not being familiar with github very much yey. Where can I make such proposal? Not planned means you are not going to make Linux version never ever?

**Comment by marcosholgado** [comment] 2024-10-13 11:32
This is the repository for the Android browser and we only accept issues within our Android app. I closed it as not planned because our team won't be able to plan/do that since we only focus on Android. It doesn't mean that DuckDuckGo will never make a Linux version, just that this is not the team that'll work on it. I'll pass that feedback to the product team so they have another data point when it comes to prioritize it.

**Comment by rafnov** [comment] 2024-10-13 11:36
Do you have separate teams for other currently supported systems? I have seen MacOS, iOS and Windows versions to download. Going to try on Windows now.
