### ISSUE TITLE
These permissions are unnecessary and against privacy

### ISSUE THREAD

**Issue by serrq** [duckduckgo/Android#4725] opened 2024-07-07 13:18 UTC
### Describe the bug

Your app knows which phone number I am calling, my device ID, which apps are installed on my device, and it has the capability to change autonomously my audio settings (without my knowledge or permission).

### How to Reproduce

Install the app. Thats all.

### Expected behavior

Remove those permissions.

![1000114131](https://github.com/duckduckgo/Android/assets/113377431/952bbf24-27ed-4508-b2eb-0d77cc21d24d)

### Environment

```markdown
Android app (fdroid)
```

**Comment by joshliebe** [comment] 2024-07-07 18:10
I reviewed these permissions and they are required to perform these functions:
- `android.permission.QUERY_ALL_PACKAGES`: Required to launch app links and for the search widget to show apps in the autocomplete results (App links can be enabled/disabled in settings and the search widget is optional).

- `android.permission.READ_PHONE_STATE`: Required to provide the option to pause the VPN while a user is in a Wi-Fi call. Without this, Wi-Fi calls may drop while the VPN is enabled (The user’s consent is required when enabling “Pause VPN During Wi-Fi Calls” in VPN settings).

- `android.permission.MODIFY_AUDIO_SETTINGS`: Required to provide mic functionality to websites that request it (The user's consent is required before the mic is accessed).

Thanks for the input but since these permissions are required to provide the above functionality, this is not a bug. Closing.

**Closed by joshliebe** 2024-07-07 18:10 UTC
Labels: bug, needs triage
