### ISSUE TITLE
Popup for saving files

### ISSUE THREAD

**Issue by FlorianSb** [duckduckgo/Android#581] opened 2019-08-29 22:11 UTC
I think a useful extension for the browser would be to ask if you want to save a file. How Firefox does it

![Screenshot_20190830-000523_Firefox_Klar](https://user-images.githubusercontent.com/54689374/63979742-e4544800-cab9-11e9-8565-1c26243d5f29.png)

**Comment by subsymbolic** [comment] 2019-10-14 11:17
Closing as this is a duplicate of https://github.com/duckduckgo/Android/issues/400. Thanks for submitting it though, it's a good suggestion.

**Closed by subsymbolic** 2019-10-14 11:17 UTC
Labels: duplicate
