### ISSUE TITLE
DuckDuckGo for Android doesn't detect the customized font

### ISSUE THREAD

**Issue by aswedaw** [duckduckgo/Android#1655] opened 2022-01-06 23:29 UTC
### Describe the bug

DuckDuckGo for Android should detect whether the device use customized font or factory default font. If not, DuckDuckGo for Android
won't render Myanmar Unicode properly on China ROM devices produced with Android 10 Zawdecode font.

### How to Reproduce

By using China ROM devices with Zawdecode font as factory default font, when pay a visit to All Email clients for Android should detect whether
the device use a customized  font or factory default font at first. If not,it won't work for 
Myanmar Unicode properly.
Please pay a visit to VOA Burmese website,
https://burmese.voanews.com

### Expected behavior

Customized font should be detected
at first for Southeast Asian Indigenous languages.

### Environment

```markdown
- DDG App Version:106
- Device:Redmi 7 China ROM
- OS: Android 10 with Zawdecode font as factory
default
```

**Comment by cmonfortep** [comment] 2022-01-12 13:53
Shouldn't be the OS the one providing the font to all apps instead of apps using a specific font? Closing this as not a bug. Thanks.

**Closed by cmonfortep** 2022-01-12 13:53 UTC
Labels: bug, needs triage
