### ISSUE TITLE
[Bug] System Default appearance doesn't change to dark mode along the system's current theme

### ISSUE THREAD

**Issue by raymond-1227** [duckduckgo/Android#1939] opened 2022-05-14 07:12 UTC
### Describe the bug

System Default appearance (the theme picker) doesn't change to dark mode if user is currently on dark mode, it still persists on dark mode. Dark mode (still) does work, the auto theme changing one which is "System Default" doesn't.

### How to Reproduce

**Note: All steps should be done in Android system appearance dark mode**
1. Go to DuckDuckGo settings
2. Under General, click on Theme
3. Select "System Default" and set theme
4. See the problem

### Expected behavior

It should change to dark mode

### Environment

```markdown
- DDG App Version: 5.123.0
- Device: realme 7 5G (RMX2111)
- OS: Android 11
```

**Comment by vatonbero** [comment] 2022-05-26 12:09
Can confirm this on Android 11 and DuckDuckGo Android App 5.125.1. Application is not honouring system themes and not following them.

It is worth mentioning that websites **are** changing colour scheme depending on DuckDuckGo Android App theme settings settings, if visited website supports dark and light schemes. So, example:
- set "dark" theme manually in DuckDuckGo Android App
- visit github or DDG search engine
- notice dark colour scheme, honouring DuckDuckGo Android App settings

**Comment by cmonfortep** [comment] 2022-05-26 16:33
I'm trying to follow the steps described above and I was not able to reproduce the issue. Any further information?

When I change to system theme (from light or dark), the theme app reacts as expected.

@vatonbero which device you have? is this specific of xiaomi devices?

**Comment by cmonfortep** [comment] 2022-05-26 16:35
I see we have same issue reported in https://github.com/duckduckgo/Android/issues/1729

Closing this as duplicate.

**Closed by cmonfortep** 2022-05-26 16:35 UTC
Labels: bug, needs triage
