### ISSUE TITLE
HTML5 audio controls

### ISSUE THREAD

**Issue by usabilitest** [duckduckgo/Android#473] opened 2019-04-13 22:33 UTC
There seems to be an issue with PLAY control of HTML5 audio element in DuckDuckGo on Android.

**Comment by subsymbolic** [comment] 2019-04-16 08:20
Thanks for reporting this, we will investigate.

**Comment by subsymbolic** [comment] 2019-04-16 08:49
I can confirm that tapping the play button does nothing on https://tekeye.uk/html/html5-video-test-page however hitting the sound button and THEN pressing play does work. I have opened this up to the community to fix.

Internal task reference: https://app.asana.com/0/414730916066338/1118831380832661.

**Comment by subsymbolic** [comment] 2019-04-17 13:27
It looks like this issue can be solved by turning on `hardwareAcceleration` in the manifest. I'll test and include that in the next release. Thanks again for reporting @usabilitest.

**Comment by subsymbolic** [comment] 2019-04-18 11:05
This issue seems to be os specific (see comment in https://github.com/duckduckgo/Android/pull/474). The html5 video play button works fine on
- Lollipop devices
- Q devices
- all emulators

And does not seem to work on:
- Pie devices

We have not yet checked Marshmallow, Nougat or Oreo so these may be affected too.

It may be possible to overcome the issue with some javascript touch magic. I'll continue to leave this task open to the community.

**Comment by CristianMG** [comment] 2019-04-22 19:18
Hi 

I´m trying to reproduce the error, I have discovered that in my Xiaomi MI8 if I install after deleting all data(uninstall the application) reproduced video is a success, it seems that reproduction video is broken after deleting tabs and data inside the app.

I don't see any log error suspect moreover I will attach logs in this comment and video 

XIAOMI MI8 
Android version: 9
MIUI Version: GLOBAL 10.2.1 Stable 10.2.3(PEAMIXM) 

I will try to get more information about the error

Greetings

https://we.tl/t-2TYm2TXerV

**Comment by nicolashleon** [comment] 2019-05-06 23:07
Hi! 

I'm just trying to provide some additional information on the issue as well as the previous investigation on #474

After trying the release and develop versions of the app both seem to be working as expected for the following environment:

- **DDG Android App Version** 5.23.0(release) and 5.24.0(develop)
- **Device** Pixel 2
- **OS Version** Android 9
- **Chrome Version** 74.0.3729.136

In my opinion, this might be related to the WebView version or the OS but we will need to have some extra data regarding the environments in which the error was successfully reproduced to narrow the cause down.
 
Hope this helps!

**Comment by subsymbolic** [comment] 2019-05-24 02:09
I can confirm that this is resolved in more recent versions of WebView/Chrome 74.0.3729.157. Thanks for the input all.

**Closed by subsymbolic** 2019-05-24 02:09 UTC
Labels: bug, help wanted
