### ISSUE TITLE
[Bug] DuckDuckGo Privacy Browser prevents user to block tracking at some sites

### ISSUE THREAD

**Issue by huuhaa** [duckduckgo/Android#1823] opened 2022-03-23 00:38 UTC
### Describe the bug

There are some sites which ddg has make dicision to not only disable tracking protection, but to prevent user even manually enable it. I tested with desktop browser with ddg addon on it, it also disabled tracking protection by default, but at desktop it's possible to enable it. Site will work fine when enabled, exept for videos which can't be played.

Still that shouln't ever be reason to prevent user manually enable tracking protection in privacy browser! If that is done, it is clearly a bug. Right solution  would be let user always decide should tracking protection be enabled even if some issues could be there. Better solution would be to figure out how could that one fuction, videoplayback be fixed even when adds and other tracking blocked and use this as default. Still let user to enable full tracking protection.

Example website:

https://www.iltalehti.fi/

and for video examples:

https://www.iltalehti.fi/iltv

### How to Reproduce

1. Go to https://www.iltalehti.fi/ using Duckgduckgo for Android
2. Check status of tracking protection
3. Try to enable tracking protection
4. See how much ads etc are alongside the articles igf you open one.

### Expected behavior

Expected behavior, especially for **privacy browser** should be:

**Always let user decided** does (s)he want to enable tracking protection or not. **Never prevent** that action from user.

### Environment

```markdown
- DDG App Version: 5.116.0 (51160000)
- Device: Mobile Phone
- OS: Android
```

**Comment by eccul** [comment] 2022-03-24 07:10
There's a warning that says "We temporarily disabled Privacy Protection as it appears to be breaking this site." so it might as well ve intentional. I wonder how *much* does it break the site though

**Comment by huuhaa** [comment] 2022-03-24 17:17
@eccul Yes it's intentional, but not temporarely, but permanent currently (ok, one can say ex. 1 year temporarily).

Even if it's intentional, I consider it a bug, or whole "privacy browser" branding should be removed. Like said, it's not possible to enable by user, when risk for breaking site would be on user. At desktop (using ddg addon) user can enable this manually, but on Android there's no way currently.

Anyway with privacy browser, control should be always at user, not "We temporarily disabled Privacy Protection as it appears to be breaking this site." with no option for user to enable it with own risks. Current state is almost like site "orders" browser when to disable tracking protection.

**Comment by cmonfortep** [comment] 2022-03-25 09:45
Thanks, @huuhaa for reaching us.

Our current behavior (on the mobile app) is intended but it will change to the one you expect (same as in desktop). Basically, as @eccul mentioned, we temporarily disable privacy protections in some sites based on users' broken site reports + manual triage. As a mitigation, we implemented the current behavior (disabling protections for known problematic sites), but we will allow users to disable it manually.

I'm going to close this issue since right now it's not a bug (and we prefer to keep issues only for bugs in our app). I will share this feedback to the team that maintains that feature.

**Closed by cmonfortep** 2022-03-25 09:45 UTC
Labels: bug, needs triage

**Comment by huuhaa** [comment] 2022-03-28 15:36
@cmonfortep Thanks for information! Is there any place where we, users can follow what changes are at the pipeline etc? This project is difficult to trying to make something change or improve, cause only bugs here and at discussion section feature requests are silenced to death, or that how it feels when comparing to other projects.

So if there's good place to follow what's coming up, at least there would be less suggestions & feedback about those things which will change soonish.. But also would be nice if there would be way for user actually have some effect to the project at lest with some feature request etc. Now it feels like almost every feature request people have suggested has been spoken to the walls.  I assume that's not your goal though.

**Comment by cmonfortep** [comment] 2022-03-30 10:00
The most incoming things are in the pull request section, but we don't have a public place where to check our mid/long-term roadmap. That's something we discuss internally with many stakeholders, based on our company strategy, user feedback, people available, etc.

Bugs reports are important for us, that's why we wanted to give them enough space (github issues). User feedback is consumed in a different way: users can share feedback directly from the app or via GitHub discussions. Internally we consume that feedback on a daily basis, and things get prioritized internally based on that.
