### ISSUE TITLE
[Bug] Follow up on unwanted "X-Requested-With" header issue

### ISSUE THREAD

**Issue by AlanCPSC** [duckduckgo/Android#2385] opened 2022-10-11 22:27 UTC
### Describe the bug

After waiting a few years and checking back on the status of DuckDuckGo Android, I notice that the following is still an issue.

In every request, we still seem to be sending this extremely frustrating fingerprint ridden header `X-Requested-With`.

```
{
    "args":{
    },
    "headers":{
        "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Accept-Encoding":"gzip, deflate",
        "Accept-Language":"en-CA,en-US;q=0.9,en;q=0.8",
        "Host":"httpbin.org",
        "Sec-Fetch-Dest":"document",
        "Sec-Fetch-Mode":"navigate",
        "Sec-Fetch-Site":"none",
        "Sec-Fetch-User":"?1",
        "Sec-Gpc":"1",
        "Upgrade-Insecure-Requests":"1",
        "User-Agent":"Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.79 Mobile DuckDuckGo/5 Safari/537.36",
        "X-Requested-With":"com.duckduckgo.mobile.android"
    },
    "origin":"000.111.222.333",
    "url":"https://httpbin.org/get"
}
```

Can you fine folks follow up on this issue and see if there is any way to overcome this obstacle yet in 2022?

I have attached some related chromium links - I believe the Google Devs may be persuaded if DuckDuckGo nudges them.

[Issue 960720: Sending X-Requested-With header to every website is a device fingerprinting risk](https://bugs.chromium.org/p/chromium/issues/detail?id=960720)

[Issue 1295213: Implementation Bug: API for controlling X-Requested-With header in Webview](https://bugs.chromium.org/p/chromium/issues/detail?id=1295213)

### How to Reproduce

N/A

### Expected behavior

N/A

### Environment

```markdown
- DDG App Version: 5.138.1
- Device: Android Device
- OS: Android 13
```

**Comment by cmonfortep** [comment] 2022-10-13 19:26
Thanks @AlanCPSC, and thank you as well for sharing those issue trackers with us. As you can see, this is still a limitation of the webview component. We are aware of it and we are internally working on pushing for improvements on the WebView.

I'm going to close this issue because it's not a bug (it would be a  feature we would like to support) and we only keep bugs as issues. But I will share this request internally.

**Closed by cmonfortep** 2022-10-13 19:26 UTC
Labels: bug, needs triage

**Comment by AlanCPSC** [comment] 2022-10-30 01:04
@cmonfortep I found a potential solution to this problem. Please consider replacing `WebView` with `GeckoView`.

https://github.com/mozilla/geckoview
