### ISSUE TITLE
[Bug] Adding a favorite also adds a bookmark

### ISSUE THREAD

**Issue by danpla** [duckduckgo/Android#3376] opened 2023-07-22 22:26 UTC
### Describe the bug

Bookmarks and favorites have always been independent, but in one of the recent updates, adding a favorite began to entail adding a bookmark. At the same time:

* Removing the favorite does not delete the implicitly added bookmark, but deleting that bookmark removes the favorite.
* Changing the favorite (title or URL) changes the bookmark, and vice versa.

The above two problems don't happen with favorites without bookmarks, i.e., those that were added in previous DuckDuckGo versions - they behave as usual. That is, if you open such a favorite and add a bookmark, then deleting the bookmark will not delete the favorite, and both can be edited independently.

### How to Reproduce

1. Add a favorite.
2. Note that the bookmark is added as well.

### Expected behavior

Bookmarks and favorites should be independent, as in the previous versions.

### Environment

```markdown
- DDG App Version: 5.163.0 and 5.164.2
- Device: Armor X7
- OS: Android 10
```

**Comment by marcosholgado** [comment] 2023-08-04 10:15
Thanks for reaching out to us. The behavior described is by design. In our system, a Favorite is essentially a "favorited" bookmark. When you designate a page as a favorite, it suggests that it's a page of interest. Consequently, it's automatically displayed on the New Tab for easy access and can be used more reliably in autofill.

There is potential for follow up changes that we will discuss with the team but for now this is working as it was designed so I'm going to close this.

**Closed by marcosholgado** 2023-08-04 10:15 UTC
Labels: bug, needs triage
