### ISSUE TITLE
Enhanced grade 'A' not shown correctly in Privacy Dashboard

### ISSUE THREAD

**Issue by hundertzwoelf** [duckduckgo/Android#802] opened 2020-04-28 17:30 UTC
![Screenshot_20200428-191509](https://user-images.githubusercontent.com/64233744/80517518-81d38480-8985-11ea-8aea-8a601ecde965.jpg)

I think this only happens with 'A'.  

App version: 5.52.5
Device/OS: OP6, OOS10

**Comment by cmonfortep** [comment] 2020-05-01 07:10
Thanks for reporting this. I was able to reproduce it. 👍 

Created an internal task https://app.asana.com/0/414730916066338/1173797528771833/f

**Comment by AndrewR8** [comment] 2020-05-01 13:33
@cmonfortep it seems to me that there is no need to reproduce it, because this is a feature of this image resource

**Comment by cmonfortep** [comment] 2020-05-12 05:38
This is fixed now. It will be included in our next release. Thanks.

**Closed by cmonfortep** 2020-05-12 05:38 UTC
Labels: bug
