### ISSUE TITLE
Sliding up slightly viewing images hides toolbar

### ISSUE THREAD

**Issue by acc85** [duckduckgo/Android#417] opened 2019-01-14 19:37 UTC
Steps to replicate:
1. Search for something that will result in many image shown when selecting the images tab in browser
2. select the "Images" tab in browser
3. Select an image
4. Slide up slightly without dismissing the image.

Result:
Toolbar is slightly pushed up without going back down without backgrounding then foregrounded the app, or slightly sliding back down.

Possible solution:
Have the toolbar statically in place instead of sliding with the image

**Comment by cmonfortep** [comment] 2020-06-09 15:11
Testing this in our current latest version and I can't reproduce this problem anymore. Most probably this has already been fixed.

I will close this issue in a few days if no one disagrees. 🖖

**Closed** 2020-06-19 09:34 UTC
