### ISSUE TITLE
[Bug] Not able to open apps via links regardless of "Open links in apps" settings

### ISSUE THREAD

**Issue by GabeK0** [duckduckgo/Android#3809] opened 2023-11-06 16:37 UTC
### Describe the bug

Clicking a link to open an app recently stopped working, regardless of your "Open links in apps" setting within DuckDuckGo. Instead, just a new tab of DuckDuckGo is opened. We use web views + app links for our mobile log in at [Ramp](https://ramp.com/) and recently started seeing this issue for our log in for Android users on DuckDuckGo.

https://github.com/duckduckgo/Android/assets/3013261/cbd8887d-776f-490d-97bc-1d679ede45db

### How to Reproduce

Find a link that's supposed to open an app, it doesn't open the app and instead opens a new tab

### Expected behavior

Expected behavior: Clicking an app link opens the app

### Environment

```markdown
- DDG App Version: 5.177.1
- Device: Pixel 6 
- OS: Android 13
```

**Comment by CrisBarreiro** [comment] 2023-11-07 09:29
Hi @GabeK0, thanks for reporting this issue!
We've tried to reproduce it on Ramp's production site, but weren't able to. Could you please let us know if you're facing the same issue on the prod site or only the QA one?

**Comment by GabeK0** [comment] 2023-11-07 19:49
@CrisBarreiro thanks for looking into this, we really appreciate it.

So to be clear, this is not happening on Ramp's production site exactly, this is happening within our Android app's log in flow which uses a web view for log in.

Once you complete log in within the web view and click "Continue to the app", it's supposed to return you to the Ramp Android app.

In the past, we've seen issues with our log in for Android users using DuckDuckGo as their default browser, such as when users have gone into their DuckDuckGo app settings -> Permissions -> Open Links in Apps -> and had selected "Never." Unsurprisingly, if they do select this setting, our "Continue to the app" mobile web view button is not able to redirect said user into our Android app. That is expected behavior, as your the DuckDuckGo app's settings are working as intended.

Recently however, it seems that our "Continue to the app" web view button is not redirecting users into our Android app, regardless of their DuckDuckGo "Open Links in Apps" settings. Even if they have that setting set to "Always," they still aren't redirected into the app. We currently believe this to be a regression within DuckDuckGo, as it was previously working with DuckDuckGo and only recently stopped working, and we haven't seen any issues with any other Android browsers.

**Comment by CrisBarreiro** [comment] 2023-11-08 14:52
Thanks for the detailed explanation @GabeK0!

I did some testing using the Ramp Android app, but still couldn't reproduce the issue. The only difference I can see is that we're using SSO, while you're using username and password. Even though this is most likely not the problem, could you please test again using SSO?

Also, could you please check which webview version your testing device is using?

**Comment by GabeK0** [comment] 2023-11-08 21:13
@CrisBarreiro Thank you so much for helping test and investigate.

I'm unfortunately not easily able to test with SSO due to Okta SSO restrictions on our end.

At any rate though, after reproing the issue several more times I tried uninstall + reinstalling DuckDuckGo and that seemed to fix it. Not sure if there's somehow some sort of corrupted cache state or a similar such weird edge case that can happen to cause this issue, but the fresh installation of DDG fixed it even though I'm still on the same version of the app (5.177.1).

I think we're good to close this issue out and I can re-surface it with more details if we encounter it again.

**Comment by CrisBarreiro** [comment] 2023-11-09 08:42
Thanks @GabeK0! I tried selecting "Never" and then switching back to "Always" to check if there was some issue when changing states but it worked as expected. I'll keep an eye in case I see it again, but for now I'll close this issue. Absolutely, in case you encounter it again, please feel free to re-surface!

**Closed by CrisBarreiro** 2023-11-09 08:42 UTC
Labels: bug, needs triage

**Comment by GabeK0** [comment] 2023-11-09 16:23
Sounds good, thank you!
