### ISSUE TITLE
[Bug]  ERR_TOO_MANY_REDIRECTS could happen when multiple redirects happen

### ISSUE THREAD

**Issue by hotchemi** [duckduckgo/Android#1412] opened 2021-09-07 03:59 UTC
### Summary

I've seen the following error screen when trying to launch https://note.designing.jp/n/n9a5c60967d23.
The reason is obviously there're some redirects to finally land on the final destination.

<img src="https://user-images.githubusercontent.com/471318/132281770-c6820690-2880-4bf4-81dd-3351b3c323b7.png" width="300" />

### Root Cause

Haven't spent so much time for this but presumably we can cope with by tweaking `WebSettings`.
  - ref: https://stackoverflow.com/questions/45879809/android-webview-err-too-many-redirects

### How to Reproduce

- Open https://note.designing.jp/n/n9a5c60967d23 with DuckDuckGo Android app
- See the error screen above

### Expected behavior

- Open the URL without any errors
  - Confirmed Chrome and Firefox can open the URL.

### Environment

```markdown
- DDG App Version: 5.94.3
- Device: Pixel3
- OS: Android11
```

**Comment by hotchemi** [comment] 2021-09-07 04:00
I can spend some time on the weekend(if we can agree this is the issue to address)!

**Comment by cmonfortep** [comment] 2021-09-21 07:59
@hotchemi I was trying to reproduce the issue with the link you provided, and it seems to be fixed now. Maybe there was an issue also on their side as well.

We haven't fixed this issue in our app, so it may still happen in some scenarios. Please confirm you can visit that site.

We can look again into this issue next time we detect another link failing that other browsers support.

**Closed by cmonfortep** 2021-09-21 07:59 UTC
Labels: bug, needs triage

**Comment by hotchemi** [comment] 2021-09-24 11:29
Thx for the confirmation. I've also confirmed they reduced the number of redirects probably 🙇
