### ISSUE TITLE
[Translation] No translation on the information page for duckduckgo on mac

### ISSUE THREAD

**Issue by FSaurenbach** [duckduckgo/Android#2597] opened 2022-12-04 11:06 UTC
### Describe the bug

There is no DE translation for this site.
![Screenshot_20221204-120013_DuckDuckGo](https://user-images.githubusercontent.com/87531743/205486952-faf60bae-dd2a-4ebd-8ef0-82deb6bb6eca.png)

### How to Reproduce

On a phone with the German language go to "Einstellungen" and on to "Duck Duck Go Desktop App"

### Expected behavior

No translation here: Everythingd in English.

### Environment

```markdown
- DDG App Version: 5.143.1 ml
- Device: Galaxy A13 5G
- OS: One UI
```

**Comment by cmonfortep** [comment] 2022-12-16 11:38
Thanks, I've shared this feedback with our macOS team. Probably a known thing since the macOS browser is only available in English at the moment. Closing as not a bug.

**Closed by cmonfortep** 2022-12-16 11:38 UTC
Labels: bug, needs triage
