### ISSUE TITLE
Info tab goes off while viewing images

### ISSUE THREAD

**Issue by Lalisfeed** [duckduckgo/Android#1319] opened 2021-07-15 06:15 UTC
**Describe the bug**
The image info tab goes off/down when image is opened having search bar visible.

**How to Reproduce**
1. Go to the App
2. Search for something and open images tab.
3. Load an image when the search bar is visible & load the image when search bar is not 

**Expected behavior**
Info tab can be seen (everything fits into the screen i.e viewing image, info tab with having fixed search bar and there would be no need to scroll)

**Smartphone:**
 - DDG App Version: 5.90.00
 - Device: Xaomi
 - OS: Android 10
 
The screenshots are here
 1. When search bar is visible and image is opened
 2. When search bar is hidden and image is opened

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/59479762/125735034-dc30e86f-9772-49e9-9fb3-19779470d34f.jpg">
</td>
<td>
<img src="https://user-images.githubusercontent.com/59479762/125735071-86024a54-b2e9-4444-8452-60fb9290a6c6.jpg">
</td>
</tr>
</table>

**Comment by prashantkumar-cmd** [comment] 2021-07-18 08:15
i want to work on it . is it available?

**Comment by Ammako** [comment] 2021-07-19 22:56
This is the same issue as #914 #638

**Comment by cmonfortep** [comment] 2021-07-25 19:23
As @Ammako pointed out, this is caused by the problem described in https://github.com/duckduckgo/Android/issues/914 and we are open for contributions to fix that bug.

Closing this as duplicated.

**Closed by cmonfortep** 2021-07-25 19:23 UTC
Labels: bug, needs triage
