### ISSUE TITLE
[Bug] (java.lang.IllegalStateException: Already closed) appear frequently

### ISSUE THREAD

**Issue by Terrible-Tornado** [duckduckgo/Android#2596] opened 2022-12-03 11:40 UTC
### Describe the bug

The bug like the following one appears in the logcat frequently, hope the stack trace could help:

FATAL EXCEPTION: pool-8-thread-1
Process: com.duckduckgo.mobile.android.debug, PID: 30685
java.lang.IllegalStateException: Already closed
	at leakcanary.internal.activity.db.ScopedLeaksDb$DbOpener.checkClosed(ScopedLeaksDb.kt:69)
	at leakcanary.internal.activity.db.ScopedLeaksDb$DbOpener.getWritableDatabase(ScopedLeaksDb.kt:51)
	at leakcanary.internal.activity.db.Db$execute$1.invoke(Db.kt:35)
	at leakcanary.internal.activity.db.Db$execute$1.invoke(Db.kt:9)
	at leakcanary.internal.activity.db.Io$execute$2.invoke(Io.kt:44)
	at leakcanary.internal.activity.db.Io$execute$2.run(Io.kt:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### How to Reproduce

Don't know where is this come from, many actions will trigger this

### Expected behavior

Normal operation instead of often fail back to the android launcher or get a white screen

### Environment

```markdown
- DDG App Version: 5.140.0
- Device: Emulator Google Pixel 2
- OS: Android 9.0
```

**Comment by cmonfortep** [comment] 2022-12-16 12:04
Probably you are running a debug build. We use leakcanary to detect possible leaks in our app. The stacktrace indicates is coming from that library instead of our app.

Closing as not a bug.

**Closed by cmonfortep** 2022-12-16 12:04 UTC
Labels: bug, needs triage
