### ISSUE TITLE
Delay in search results

### ISSUE THREAD

**Issue by Amanraj13** [duckduckgo/Android#1087] opened 2021-02-04 17:20 UTC
**Describe the bug**
Delay In search results

**How to Reproduce**
1. In the search bar type anything
2. Tap search
3.See the delay in loading results

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**

I am facing delay in search results. For example if I search for a place , for few seconds (7-8) there appears a blank white screen. It is quite strange as ut doesn't happens with any other browse that I use
**Smartphone (please complete the following information):**
 - DDG App Version: (5.75.1)
   App Info
 - Device: [Motorola G9]
 - OS: [Android 10]
 - If applicable, add screenshots to help explain your problem.

**Comment by cmonfortep** [comment] 2021-02-04 17:35
Just to confirm, when you say it doesn't happen with any other browser, you mean using another browser and doing the same search with duckduckgo, right? 

Thanks

**Comment by Amanraj13** [comment] 2021-02-04 18:15
Yup. When i use search in duckduckgo android app i get blank screen for few seconds before the result is displayed. But if search the same thing in another browser i do not face any such issue

**Comment by bluetoothfx** [comment] 2021-02-04 18:19
@Amanraj13 could you please share a gif/small video?

**Comment by Amanraj13** [comment] 2021-02-04 18:24
Well.. i uninstalled the app. I will need to install it again

**Comment by bluetoothfx** [comment] 2021-02-04 18:26
If it is possible for you please share a video. It will help people to understand your reported issue more clearly.

**Comment by cmonfortep** [comment] 2021-02-08 14:10
@Amanraj13 If you manage to unistall the app again, please provide us a gif or a video, it wil be very helpful to understand the issue. Thanks.

**Comment by cmonfortep** [comment] 2021-02-26 10:24
Closing this issue as we haven't received any similar feedback or bug reports similar to the described on this issue. We can't reproduce the error. Thanks.

**Closed by cmonfortep** 2021-02-26 10:24 UTC
Labels: bug, needs triage
