### ISSUE TITLE
Do not sleep on full-screen

### ISSUE THREAD

**Issue by nhatzHK** [duckduckgo/Android#637] opened 2019-11-28 19:25 UTC
When watching a video on the Android app in full-screen, the screen dims and subsequently goes to sleep. It's kind of annoying to keep tapping the screen to keep it awake, or worse, to remove the display settings directly.

**Comment by AndrewR8** [comment] 2020-04-07 10:50
@nhatzHK Any particular website to test this scenario?

**Comment by nhatzHK** [comment] 2020-04-11 01:05
Woah I tried to find the websites where I observed that behaviour but I can't find any. I was sure it happened on YouTube, but it doesn't. Could it be that this was fixed incidentally somewhere else?

**Comment by cmonfortep** [comment] 2020-04-13 20:39
Could it be, but not that I know :)
I also tested it and I was not able to reproduce that behavior.

I'm going to close the issue, it seems the issue is gone. But please, do not hesitate to open it again if the issue appears again, and share with us how to reproduce it.

Thanks!

**Closed by cmonfortep** 2020-04-13 20:39 UTC
Labels: enhancement
