### ISSUE TITLE
Downloads fail on some websites

### ISSUE THREAD

**Issue by uraza** [duckduckgo/Android#1010] opened 2020-11-11 21:01 UTC
**Describe the bug**
On some websites, downloads are failing (even when all protections are disabled).

**How to Reproduce**
1. Go to https://media.interieur.gouv.fr/deplacement-covid-19/
1. Fill the form and tap on "Générer mon attestation"
3. The browser prompts to download the file (left screenshot).
4. Tap "Continuer", the download fails (right screenshot).

![image](https://user-images.githubusercontent.com/3456223/98863718-0f317e80-2469-11eb-9639-e666e7937c9e.png)![image](https://user-images.githubusercontent.com/3456223/98863796-2ec8a700-2469-11eb-8410-7cee5b1169aa.png)

**Expected behavior**
The file should be downloaded to the device, I checked with Chrome to confirm that it works.

**Smartphone (please complete the following information):**
- DDG App Version: 5.68.0 (56800) from F-Droid
- Device: Samsung Galaxy A51 5G
- OS: Android 10

I observed the same issue on other websites in the past, but I cannot remember which ones.
Hopefully this can be addressed in one of the upcoming versions. :)

Thanks.

**Comment by bonninf** [comment] 2020-11-13 10:13
I get the same issue, and to complete the information above, the download error is due to the fact the gouv.fr site uses `blob:`. The url is: "blob:https://media.interieur.gouv.fr/5adc53dd-f097-468e-a258-22dcfb3175f1 "

The download is working fine with other browser mobile apps such as Chrome, Safari...

Do you have a plan to fix this issue? Thanks

**Comment by cmonfortep** [comment] 2020-11-13 17:06
Cool, thanks for letting us know, and always really helpful to share examples on how to reproduce the issue.

We will try to prioritize a fix. I've created an internal task (https://app.asana.com/0/414730916066338/1199183428824728/f) to keep track of it.

However, if anyone from our opensource community wants to take it, we will give support. Thanks!

**Comment by bonninf** [comment] 2020-11-14 09:23
Hi Cristian, thanks for your response.

For your information, I'm trying to solve the issue by using XMLHttpRequest.

**Comment by cmonfortep** [comment] 2020-11-14 09:54
Thanks @bonninf, please check our `DataUriDownloader` in case there is any similarity between uri types and blob types. Haven't checked tho.

**Comment by bonninf** [comment] 2020-11-17 14:09
I have a solution now which is working fine with the web site: https://media.interieur.gouv.fr/deplacement-covid-19/

How can I provide this fix to you?

**Comment by cmonfortep** [comment] 2020-11-20 20:21
@bonninf please refer to our [contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code). Just send us a PR and we will review it.

**Comment by iamhaseebiqbal** [comment] 2021-12-14 21:46
Still having this problem.

Trying to download a PDF. Website redirects from a URL to  PDF document. I see the error, failed to download.

**Comment by cmonfortep** [comment] 2021-12-14 23:17
We are currently working on improving downloads and we will try to address all the reported issues. Could you share any link that is failing for you? We will use them to test our fixes.

**Comment by iamhaseebiqbal** [comment] 2021-12-15 10:46
@cmonfortep  I was trying to download my salary slip. Link cannot be provided unfortunately since it needs 2 factor authentication.
The link looks something like this,
https://subdomain.domain.de/api/files/document/{key}

**Comment by rtrbt** [comment] 2022-01-06 11:18
The issue is still there javascript code that creates an a element to download a blob. See the code below for a more or less minimal example. (Github does not allow to attach .html files). Downloading blob.json works with other browsers I've tested (Firefox, Chrome, Opera, Mi Browser, etc.).

```html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script type = "text/javascript">
            function downloadBlob() {
                let content = '{"a": 1}';
                let contentType= "application/json";
                let filename = "blob.json";
                let a = document.createElement('a');
                let file = new Blob([content], {type: contentType});

                a.href= URL.createObjectURL(file);
                a.download = filename;
                a.click();

                URL.revokeObjectURL(a.href);
            }
        </script>
    </head>
    <body>
        <input type="button" onclick="downloadBlob();" value="Click me"></input>
    </body>
</html>
```

**Comment by bonninf** [comment] 2022-01-19 14:18
Hi @cmonfortep 
The issue seems to exist again by using the same url as above: https://media.interieur.gouv.fr/deplacement-covid-19/
The confirmation popup "File downloaded" is no longer displayed and the downloaded file is not present inside the Android's file manager.
Shouldn't this issue be reopened?

**Comment by marcosholgado** [comment] 2022-01-19 14:54
Thanks for the info @bonninf and @rtrbt. We are currently running a project to hopefully fix once and for all our download issues, we'll re-add this to the list :)

cc/ @anikiki, feel free to close once solved

**Comment by Devbymitch** [comment] 2022-01-25 20:53
I got this error when trying to download from: https://bit.ly/csos_latest_apk which forwards to google drive here: https://drive.google.com/file/d/18EE975b_4aroE7UCx3z64kwnJ3fIm27V/view
duckduckgo v5.109.0 on samsung flip3, hopefully that helps at all

**Comment by designzwang** [comment] 2022-01-26 11:28
@marcosholgado  - 

> We are currently running a project to hopefully fix once and for all our download issues, we'll re-add this to the list :)
> 

May I add an observation, that should also be considered when working on download problems:
Since there is no "download this file/download this link" in the context menu when pressing a link to a file, files must be opened in the browser window before downloading.  When doing  this with files that are under http basic protection , the display/playing of a file in the browser works, but then the download fails. This is because using the download context menu causes an additional HEAD request which is agnostic of the existing authentication in the session.  

This is the corresponding server log of such a session:  mp3 file in a http auth protected directory is being requested and played in the browser , then in the player widget the ...->Download menu is used. Result: download fails.


`# request for file-list: OK
example.com:80 11.22.33.44 - username [26/Jan/2022:00:57:59 +0100] "GET /basic-auth-protected-path/file-list HTTP/1.1" 200 29621 "-" "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 DuckDuckGo/5 Safari/537.36"
# request for playing a file in browser: works
example.com:80 11.22.33.44 - username [26/Jan/2022:00:57:59 +0100] "GET /basic-auth-protected-path/some-song.mp3 HTTP/1.1" 200 1929600 "http://example.com/basic-auth-protected-path/file-list" "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 DuckDuckGo/5 Safari/537.36"
example.com:80 11.22.33.44 - username [26/Jan/2022:00:57:59 +0100] "GET /basic-auth-protected-path/some-song.mp3 HTTP/1.1" 206 3229852 "http://example.com/basic-auth-protected-path/some-song.mp3" "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 DuckDuckGo/5 Safari/537.36"
example.com:80 11.22.33.44 - username [26/Jan/2022:00:58:04 +0100] "GET /basic-auth-protected-path/some-song.mp3 HTTP/1.1" 200 1051200 "-" "Mozilla/5.0 (Linux; Android 11; Nexus 7 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Safari/537.36"
# after hitting  the "Download" menu option in the player via the "..." Menu: Failing HEAD request because basic auth is not honored, so download fails. 
# also, there is a different useragent suddenly ...
example.com:80 11.22.33.44 - - [26/Jan/2022:00:58:06 +0100] "HEAD /basic-auth-protected-path/some-song.mp3 HTTP/1.1" 401 246 "-" "ddg_android/5.108.0 (com.duckduckgo.mobile.android; Android API 30)"
`

Browser is DDG 5.108.0 on latest Lineage 18.1 (on a nexus7)


Regards,
Ulrich

**Comment by marcosholgado** [comment] 2022-01-26 15:51
Hey @designzwang, yes we are aware of that headers and session cookies, etc are not being carried over and also working on it as part of this :).

**Comment by bonninf** [comment] 2022-02-28 10:39
Hello. I tested with DuckDuckGo 5.113.1 from the Play store on a device G One Android 7.0 by using the url: https://media.interieur.gouv.fr/deplacement-covid-19/
The PDF document is well downloaded but the name is not correct: "5e7e145d-173d-4813-b2c6-a95437451f72.PDF"
With Chrome I get the name as expected: attestation-2022-02-28_11-30.PDF

**Comment by marcosholgado** [comment] 2022-03-01 13:35
Thanks for the comment. We do have some problems with certain files (blobs in your case) where the filename is not surfaced to WebView. We should receive the filename in the content-disposition header but we are not. Chrome probably uses/does something different. In any case, we are aware of this and trying to find a solution for it.

**Comment by cmonfortep** [comment] 2022-07-07 09:56
We have improved our downloads feature and we have addressed different reported issues. Closing it, feel free to reopen if problem still happens.

**Closed by cmonfortep** 2022-07-07 09:56 UTC
Labels: bug
