### ISSUE TITLE
[Bug] Audio stutter if app is in background

### ISSUE THREAD

**Issue by dzatoah** [duckduckgo/Android#2370] opened 2022-10-07 12:02 UTC
### Describe the bug

I started a podcast (https://cre.fm/cre141-ipv4) and audio plays normally, but when I press the home button (send the DuckDuckGo app into background) the audio starts to stutter. Also there is no media control notification.

### How to Reproduce

- Play audio
- Send app to background

### Expected behavior

Audio shouldn't stutter and I would expect a media control notification.

### Environment

```markdown
- DDG App Version: 5.138.1
- Device: Fairphone 4
- OS: Android 11 - FP4.FP4G.A.170.20220920
```

**Comment by cmonfortep** [comment] 2022-10-13 19:31
Thanks @dzatoah We don't currently support playing video/audio in background mode. It would be nice to include that feature tho. I encourage you to send us feedback or feature request via our feedback setting in the app. We consume user feedback daily and features are prioritized based on user demand.

Closing this issue as it's not a bug report.

**Closed by cmonfortep** 2022-10-13 19:31 UTC
Labels: bug, needs triage
