### ISSUE TITLE
GPC setting only respected in websites used to test the setting

### ISSUE THREAD

**Issue by qflair** [duckduckgo/Android#1279] opened 2021-06-14 04:05 UTC
**Describe the bug**
GPC setting only fully supported when visiting a specific list of domains.

DuckDuckGo hardcodes a list of domains for which the GPC header is always included. Those domains are the ones users can use to test the GPC setting: https://github.com/duckduckgo/Android/blob/e5818214a7fe9a8b0f899501f32494577c2f02fe/app/src/main/java/com/duckduckgo/app/globalprivacycontrol/GlobalPrivacyControlManager.kt#L37-L41

However, this setting is only useful if it actually works on all domains, not tricking users into thinking it's working but it doesn't.

**How to Reproduce**
1. Make sure the GPC setting is enabled
2. Go to https://www.google.com/search?hl=en&q=whats%20my%20rewuest%20headets
3. Click on "What HTTP headers is my browser sending"
4. The `SEC-GPC` header is missing

When you visit https://globalprivacycontrol.org/ and click on "Test against the reference server", it shows the signal is ON.

**Expected behavior**
The `SEC-GPC` header should always be set to `1`, not only on domains advertised to check this setting.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.88.0
 - Device: All devices
 - OS: Android 10, but all versions.

**Comment by BubuAnabelas** [comment] 2021-06-14 06:35
> However, this setting is only useful if it actually works on all domains, not tricking users into thinking it's working but it doesn't.

I belive it isn't a trick, looking the blame of the file it's easy to see the PR which introduced the GPC changes and the discussion arround those lines of code [1] which are used for intercepting some requests. Besides that, there seems to be some issue arround how navigation is being done and how the GPC headers are added [2].

[1]: https://github.com/duckduckgo/Android/pull/1020/commits/41f9c7e59652ab2d81f5720c631cdd123f9a9fbb#r549351503
[2]: https://github.com/duckduckgo/Android/blob/0e3b3da63d572458de94c29c44c09f125e832e54/app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt#L531

**Comment by qflair** [comment] 2021-06-14 06:44
That's fair enough. Just seeing a hardcoded list of domains made me think this was done on purpose to make those domains "happy" (and that's the behavior).

Anyway, I reported this bug so that it hopefully gets fixed.

**Comment by cmonfortep** [comment] 2021-06-14 08:57
Hi @qflair, sorry if that code was a bit misleading without knowing how we handle the GPC signal.

We support 2 different ways to send the GPC signal, via DOM or Headers.

We do always send the DOM signal (injected via JS) every time you visit any site. 
You can check the code here -> https://github.com/duckduckgo/Android/blob/0b66bf4fc07bc37a8e47c7ce9389cda381cb4dd6/app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt#L165 Every time a new page starts loading, we inject the GPC signal.

When you directly visit any website (using the URL bar, bookmarks, favorites, etc.) the GPC header will always be present. You can test that by directly visiting the [website you posted](https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending) from our URL bar. However, we detected multiple issues when clicking links because of Webview limitations. In those cases, we needed to cancel the request triggered internally from the webview and send a new one (where we change the headers). When doing that we detected multiple issues in some scenarios (like user navigation broken or even the webview crashing). You can check our discussion with the WebView team [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1155129&q=WebViewTransport&can=2). The code you pointed out is to support known header consumers in that specific and problematic scenario.

We have a project in our backlog to investigate a workaround that will cover the case where the WebView was producing issues.

**Comment by cmonfortep** [comment] 2021-06-21 08:29
Closing this issue as not a bug.

As commented above, we have a project in our backlog to investigate further improvements ([internal link](https://app.asana.com/0/1198504124118156/1199408063425180/f))

Thanks.

**Closed by cmonfortep** 2021-06-21 08:29 UTC
Labels: bug, needs triage
