### ISSUE TITLE
[Feature Request] Improve Protection against Browser Fingerprinting

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#1646] opened 2022-01-02 11:35 UTC
The concept behind DuckDuckGo Privacy Browser is great. The tracker and ad blocking, I would say it is better than Firefox's by a million miles. One thing that is preventing me from using this app on a more permanent basis, is the lack of fingerprint protection. I know this has been an issue previously raised and it is a legitimate concern. The protection we get is very unique in a way but the fact we can be tracked by our browser's fingerprint is not so great. If you test out this (coveryourtracks.eff.org), you will notice how the fingerprint is unique. This means for all those trackers and ads not blocked, it makes it easier to track users especially with **_DuckDuckGo_** as part of the user agent. This does need to be addressed because you can't have a completely private experience unless you implement a measure to protect against browser fingerprinting. A couple of things I must mention is Brave randomizes its fingerprint and even Firefox has a preference to 'resist' fingerprinting.

**Comment by cmonfortep** [comment] 2022-01-12 13:56
Closing as this was not a bug, and user who reported the issue deleted the account.

**Closed by cmonfortep** 2022-01-12 13:56 UTC
