### ISSUE TITLE
Weird handling of URL intents, causing an extremely poor UX with Link Bubble

### ISSUE THREAD

**Issue by The0x539** [duckduckgo/android#157] opened 2015-03-02 02:10 UTC
http://imgur.com/a/KX0hJ

If options to disable intent handling are a technical impossibility, at least the way Firefox does it would be tolerable. Unless, for some reason, this is something on LB's end, but *something* is being done differently.

**Comment by thm** [comment] 2016-02-17 14:14
I'm closing this issue since this is a year old, and since this would be a non-urgent edge-case issue. @The0x539 if you're still experiencing the issue, then feel free to reopen the task with clear step on how to reproduce the issue.

**Closed by thm** 2016-02-17 14:14 UTC

**Comment by The0x539** [comment] 2016-02-17 14:17
Nah, the apps available and the ways in which they work and how Android
handles it makes it a bit of a non-issue these days.
