### ISSUE TITLE
[Bug] Searching languages in lang selection modal doesn't work

### ISSUE THREAD

**Issue by eccul** [duckduckgo/Android#1826] opened 2022-03-24 07:25 UTC
### Describe the bug

Language selection modal just closes once you tap on the 'Search languages' field

### How to Reproduce

1. Make a query that will bring the in-built translator
2. Tap on either language
3. On the modal tap 'Search languages'

### Expected behavior

You can just search for a language like usual

### Environment

```markdown
- DDG App Version: 5.116.0
- Device: Xiaomi Redmi 8
- OS: Android 10
```

**Comment by cmonfortep** [comment] 2022-03-25 10:16
Thanks for reporting this bug. I've been able to reproduce it using DDG browser, but also using other browsers as well. I've reported this bug to our frontend team, and they will take care of the issue.

For now, I'm closing this bug report, since it doesn't seem related to our Android app,

**Closed by cmonfortep** 2022-03-25 10:16 UTC
Labels: bug, needs triage
