### ISSUE TITLE
OnBackPressed closes tab when app entered through intent

### ISSUE THREAD

**Issue by christopherbasinger** [duckduckgo/Android#362] opened 2018-09-26 23:26 UTC
When I select a story in the app that I wrote it opens duckduckgo browser at the correct page but when I press the back button it closes the tab instead of going back to my app. 

I tested this on chrome and firefox and both exit app on back button pressed when entered through intent.

I found this Bug already in issue #245 my apologies  

It's quicker to uninstall your app then modify the default application settings when a user runs into this bug while using a news aggregator.

Another point to make is that your last app had an integrated news agg in it with a browser. So a majority of your initial fans are using news aggs.

**Comment by christopherbasinger** [comment] 2018-09-26 23:32
I found this Bug already in issue #245 my apologies

**Comment by christopherbasinger** [comment] 2018-09-27 00:27
And i left version device model etcetera out as requested because it's irrelevant.

**Comment by christopherbasinger** [comment] 2018-09-27 00:30
Fix it :(

**Comment by christopherbasinger** [comment] 2018-09-27 00:30
Its annoying

**Comment by christopherbasinger** [comment] 2018-09-27 00:31
I was going to have a card in my app that sent an intent with a search param for ddg browser to support it but now I can't send any users that way with this bug

**Comment by christopherbasinger** [comment] 2018-09-27 00:32
I no longer support duckduckgo browser until this is fixed.

**Comment by CDRussell** [comment] 2018-09-27 12:03
Hi @christopherbasinger, thanks for your feedback.

I get why this is annoying. I don't particularly like the number of times required to hit the back button either. And while we may sometimes want the existing behaviour, I agree that it's not the best behaviour when the user has dropped in from another app.

I'll raise this with the team as I understand the frustration. I'll close this task, since it is a duplicate of #245, and we can carry on the conversation there if there's more to add.

**Closed by CDRussell** 2018-09-27 12:03 UTC
