### ISSUE TITLE
Speedtest slower

### ISSUE THREAD

**Issue by reno-a** [duckduckgo/Android#296] opened 2018-06-25 13:40 UTC
Hello,

I notice a difference at speedtest tests with Duckduckgo app,and other WebView browser. Same with Chrome/Chromium and Firefox (nightly and other versions). Duckduckgo is always slower.

For exemple, for other WebView browsers :
- Firefox Klar/Focus Download ~21M  Upload ~ 10M Ping ~155ms
- Duckduckgo (ver. 5.7.0) Download ~7M Upload ~4M Ping ~579ms

[Motorola Moto G 2015 / LineageOS 14.1 (Android 7.1.2)]

**Comment by reno-a** [comment] 2018-07-15 07:45
Test with : http://speedtest.googlefiber.net/

**Comment by CDRussell** [comment] 2018-07-30 14:21
Thanks for reporting this. I'm going to try look into this shortly to see if there is any obvious reason for you seeing this.

**Comment by reno-a** [comment] 2018-07-31 07:32
Hello CDRussel,
Thank-you for tour answer ans help.
Two sites videos don't play all time (slowly for playing):
https://www.publicsenat.fr/direct
http://lcp.fr/le-direct/tnt
Maybe the same problem (or not)...

**Comment by reno-a** [comment] 2018-08-02 23:03
Again slowly with 5.7.5 version (f-droid)

**Comment by arunsathiya** [comment] 2018-08-24 10:37
I tested this as well and I don't see any differences at my end. If anything, Firefox and Google Chrome were slower. I think the speed test is affected by multiple parameters and DuckDuckGo Android app is specifically not causing anything, at least at my end.

**Comment by reno-a** [comment] 2018-08-24 10:52
@arunsathiya Hello,
Thank-you for the tests.
Firefox and Chrome are slower, you're right.
But the difference is with "Firefox Focus" (another privacy browser).

**Comment by CDRussell** [comment] 2018-08-24 11:25
We have an upcoming, reasonably big change to the way we upgrade requests to HTTPS if it's possible to do so.

After that change is made, I'm going to do some benchmarking and try and identify any obvious bottlenecks which could be affecting the speed.

As for the download speed testing sites, they initialise a lot of requests that the app downloads, so any bottleneck, no matter how small, is amplified by the vast number of requests it spawns. So if there was a single big file being downloaded, the difference wouldn't be as noticeable; the problem is likely the overhead incurred *per request*.

In any case, thanks for all the info and I'll be looking into this as soon as the HTTPS change is merged.

**Comment by subsymbolic** [comment] 2019-04-16 09:04
Thanks for logging this @reno-a, we are currently working on performance internally. Watch out for it in future merges/updates.

**Closed by subsymbolic** 2019-04-16 09:04 UTC
