### ISSUE TITLE
Webview positioned partially offscreen hides content

### ISSUE THREAD

**Issue by sanogueralorenzo** [duckduckgo/Android#914] opened 2020-08-21 23:28 UTC
**Describe the bug**
Any drawing app scrolls up and down while drawing. Possibly related to https://github.com/duckduckgo/Android/pull/674 makes DDG completely unusable in this matter.

**How to Reproduce**
1. Go to https://sketch.io/sketchpad/
2. Try to draw anything
3. See error

**Expected behavior**
Drawing should be able to work on any webpage with drawing canvas capabilities, coordinator layout should stop going up and down while you are drawing, making drawing impossible

**Smartphone (please complete the following information):**
 - DDG App Version: 5.62.0 zk (been there at least since I started using it half a year
 - Device: All phones
 - OS: All OS

**Comment by kwawmannanjnr** [comment] 2020-09-01 08:58
I'm new to contributing to opensource projects. Can I work on this issue?

**Comment by subsymbolic** [comment] 2020-09-01 12:17
@kwawmannanjnr definitely, we welcome PRs for any issues tagged with [help wanted](https://github.com/duckduckgo/Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22). Check out our [CONTRIBUTING.md](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md) guidelines for more information.

**Comment by cmonfortep** [comment] 2020-09-30 09:35
Information for possible contributions:
The issue is that the web view can actually off be positioned partially offscreen depending on the scrolling. When you scroll the page, the toolbar slides up, as does the web view. So only when the toolbar is fully up off screen is the web view fully positioned onscreen.
It seems to be a combo of the scroll behaviour + CoordinatorLayout that is causing the issue.

Some websites where this issue is easy to reproduce are:
- twitter.com -> Bottom bar is hidden and user needs to scroll to make it appear. Expectation is that bottom bar is visible always.
- https://sketch.io/sketchpad/ -> as described in the description

**Comment by garygreen** [comment] 2020-10-26 15:03
@cmonfortep if this issue is one that's "different and totally valid use case too" then why did you close #638 ? This issue looks complex and different the one described in that other issue. The complexity of trying to fix the sketchpad app vs bottom navbar / fixed position elements generally is a different issue imo.

**Comment by cmonfortep** [comment] 2020-10-26 16:21
Hi @garygreen, by "this one is different" I didn't want to say it's another problem, but a new scenario that we didn't know about. Both issues are affected by the same root cause.

I understand your point here, however, we didn't want to keep both issues open and decided to give this one more visibility during Hacktoberfest. I apologize if that was not clear.

In any case, we also posted [this comment](https://github.com/duckduckgo/Android/issues/914#issuecomment-701279307), which explains the root cause, and also shares the examples we commented in https://github.com/duckduckgo/Android/issues/638

**Comment by cmonfortep** [comment] 2021-01-07 16:35
Tracking this internally: https://app.asana.com/0/0/1187616573788673/f

**Comment by tvalle** [comment] 2021-01-11 23:34
Are you guys fixing this internally or could I try to tackle this?

**Comment by cmonfortep** [comment] 2021-01-12 00:05
Go for it! We are tracking this issue internally, but we haven't had time to work on that yet.

**Comment by tvalle** [comment] 2021-01-31 01:25
Unfortunately I couldn't understand what's the cause of this issue so I couldn't provide a fix. I'll try another issue to fix.

But while experimenting and trying to understand what's going I saw this behaviour: if in ``fragment_browser_tab.xml`` one sets ``android:fitsSystemWindows="true"`` on the root CoordinatorLayout and then set ``android:layout_marginBottom="?attr/actionBarSize"`` in the ``ConstraintLayout`` with id browserLayout everything works properly (sketchpad and Twitter) but the swipe up on the AppBarLayout stops working. Maybe because fitsSystemWindows interferes with the CoordinatorLayout behaviors. I know this is not a fix but maybe is a helpful tip for someone who might fix this.

**Comment by ryg-git** [comment] 2021-04-22 12:48
If it is ok, I would like to work on this issue

**Comment by kolanse** [comment] 2021-07-18 00:10
Please is this issue still open to be tackled?

**Comment by marcuswu** [comment] 2021-07-20 21:43
The above commit is unfortunately not a solution.
I'm not convinced this is the right approach for a few reasons listed below, but it could be on the right track.

- I am not 100% sure this isn't possible without subclassing `AppBarLayout.ScrollingViewBehavior`. That behavior does adjust positioning, but I haven't found where it or its parent alters view size. I haven't exhausted the search, but if the behavior can do that, it'd be best to use its ability to do so. Layout Inspector showed me that for everything else I tried, the `FrameLayout` that contains the WebView is the same size as the `CoordinatorLayout` and is pushed down by the `AppBar`, clipping the bottom of the `FrameLayout` and therefore the `WebView`
- sketch.io still scrolls while drawing and the `AppBar` still hides. This is likely because my solution uses padding instead of resizing the view which means the `FrameLayout` is still larger than the viewable area when the `AppBar` is visible. My attempts at actually resizing the view performed worse (jittery movement)
- The web page layout of twitter.com looks incorrect when scrolling is first initiated, but returns to what's expected during the scroll. I noticed that other Android browsers behave the same way, but seem to correct it faster than this. This performance difference could be due to running a debug build.

I went ahead and committed my work and pushed it up to a fork in case it furthers discussion on an actual solution.

**Comment by marcuswu** [comment] 2021-07-30 21:40
I've iterated over my earlier code and have what I believe to be a working solution. I'd love some feedback.

**Comment by hotchemi** [comment] 2021-08-28 11:14
Just noticed this issue has been addressed seemingly? Now I can use Twitter webapp normally👏

**Comment by oldergod** [comment] 2022-01-22 15:42
Why not taking into account the height of the navigation bar?

**Comment by marcuswu** [comment] 2022-04-14 13:11
I am not convinced my solution was ever really 100% correct. I did [open a PR for it](https://github.com/duckduckgo/Android/pull/1341), but it was closed because it was supposed to be working properly on the latest code. I would look again, but I have some other projects taking my time right now.

**Comment by mohammadreza-torkaman** [comment] 2022-05-20 10:50
Hey, I'd like to contribute. can I work on this issue? Does this still need help?

**Comment by AndroidPoet** [comment] 2022-06-02 08:10
I I'd like to fix this.

**Comment by nb1987** [comment] 2022-07-25 10:05
Just chiming in to provide another example where this behavior is easily reproducible:

[http://szimek.github.io/signature_pad/](http://szimek.github.io/signature_pad/)

We are leveraging the SignaturePad library in one of our projects, but this issue has meant we have to recommend our DuckDuckGo users to switch to Chrome.

**Comment by MohitMandalia** [comment] 2022-10-03 15:57
Seems to be resolved with the latest version of dev:

Tried it with version 5.138.1 on below devices
- Google Pixel 4a 
- Google Pixel 5a

**Comment by malmstein** [comment] 2023-06-23 09:48
Closing this stall issue. This doesn’t apply anymore.

**Closed by malmstein** 2023-06-23 09:48 UTC
Labels: bug

**Comment by StampixSMO** [comment] 2023-09-13 14:54
Not sure why this was closed, this is still very relevant and still appearing on versions > 5.138.1

**Comment by tommie** [comment] 2025-11-26 13:55
Dragging causes a scroll event even though the page covers the viewport. As mentioned in dupe bugs, `overscroll-behavior: none` does not seem implemented. Using `preventDefault()` for `scroll` and `mousemove` also seems to do nothing.

Here's an example that works fine with Chrome Android, but breaks with DDG: https://tommie.github.io/blockpuzzle2/

I think the issue is that attempting to scroll on a full-height page shouldn't hide the address bar. It would probably be fine if the address bar is shown due to an attempted scroll/click, but DDG also hides the address bar if "scrolling" in some direction. I.e. it either gets confused by its own scroll animation that resizes the page, or it interprets a touch drag as a scroll event without filtering to check if it has a scrollable height.
