### ISSUE TITLE
Google Ads not blocked for some websites in latest app version

### ISSUE THREAD

**Issue by donfuxx** [duckduckgo/Android#983] opened 2020-10-29 09:19 UTC
**Describe the bug**
on some websites the blocking of ad networks doesn't detect all ad trackers.

**How to Reproduce**
1. Go to the website https://www.theguardian.com/commentisfree/2020/oct/28/england-coronavirus-covid-test-and-trace-teenagers 
2. wait for page to load
3. Scroll down till you see the first google ad in the page content
4. click "B+" icon in browser address bar
5. observe "0 Trackers Blocked" text: 
![Screenshot from 2020-10-29 09-12-08](https://user-images.githubusercontent.com/8261416/97548640-4a42a500-19c7-11eb-9ff8-1f03d68e0410.png)

![Screenshot from 2020-10-29 09-18-39](https://user-images.githubusercontent.com/8261416/97549006-c6d58380-19c7-11eb-8f63-a25dc9398a9a.png)

**Expected behavior**
ads aren't visible in webpage and blocked trackers get reported in privacy report.

**Smartphone (please complete the following information):**
 - device seems to be irrelevant for this bug, can repro also on emulator
 - app version `VERSION=5.68.0`

**Comment by cmonfortep** [comment] 2020-10-30 11:09
Thanks for reporting @donfuxx . I will take a look to this issue. I was able to reproduce it on my device too (as you already pointed out), and seems like we should be blocking it.

**Comment by donfuxx** [comment] 2020-10-31 16:10
@cmonfortep Ok cool. I just checked this in the logs and it looks like it was whitelisted:

```
2020-10-31 16:05:20.024 4905-8433/com.duckduckgo.mobile.android.debug V/BrowserWebViewClient$shouldInterceptRequest: Intercepting resource https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j87&tid=UA-78705427-1&cid=752640144.1604160320&jid=1386206637&gjid=1487273755&_gid=155638529.1604160320&_u=YEDAAUAAAAAAAC~&z=102444824 type:POST on page https://www.theguardian.com/uk
2020-10-31 16:05:20.027 4905-8433/com.duckduckgo.mobile.android.debug V/TrackerDetectorImpl: https://www.theguardian.com/uk resource https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j87&tid=UA-78705427-1&cid=752640144.1604160320&jid=1386206637&gjid=1487273755&_gid=155638529.1604160320&_u=YEDAAUAAAAAAAC~&z=102444824 is whitelisted
```

**Comment by donfuxx** [comment] 2020-10-31 16:45
Actually it looks like `theguardian.com` is in the list of whitelisted domains! :thinking: 
That is strange! Any reason why it's on the white list?

`[TemporaryTrackingWhitelistedDomain(domain=calbanktrust.com), TemporaryTrackingWhitelistedDomain(domain=fidelity.com), TemporaryTrackingWhitelistedDomain(domain=vanguard.com), TemporaryTrackingWhitelistedDomain(domain=mebank.com.au), TemporaryTrackingWhitelistedDomain(domain=wellsfargo.com), TemporaryTrackingWhitelistedDomain(domain=zionsbank.com), TemporaryTrackingWhitelistedDomain(domain=bankofscotland.co.uk), TemporaryTrackingWhitelistedDomain(domain=amegybank.com), TemporaryTrackingWhitelistedDomain(domain=suntrust.com), TemporaryTrackingWhitelistedDomain(domain=tdbank.com), TemporaryTrackingWhitelistedDomain(domain=inlandbank.com), TemporaryTrackingWhitelistedDomain(domain=bank.barclays.co.uk), TemporaryTrackingWhitelistedDomain(domain=capitalone.ca), TemporaryTrackingWhitelistedDomain(domain=capitalone.com), TemporaryTrackingWhitelistedDomain(domain=onlinebanking.nationwide.co.uk), TemporaryTrackingWhitelistedDomain(domain=nbarizona.com), TemporaryTrackingWhitelistedDomain(domain=sberbank.ru), TemporaryTrackingWhitelistedDomain(domain=td.com), TemporaryTrackingWhitelistedDomain(domain=ameritrade.com), TemporaryTrackingWhitelistedDomain(domain=santander.com), TemporaryTrackingWhitelistedDomain(domain=santander.co.uk), TemporaryTrackingWhitelistedDomain(domain=aternos.org), TemporaryTrackingWhitelistedDomain(domain=theguardian.com), TemporaryTrackingWhitelistedDomain(domain=nfl.com)]`

**Comment by cmonfortep** [comment] 2020-10-31 16:54
Usually it's to avoid sites breaking when blocking trackers until we know how to avoid that. I can't confirm you what's the reason behind each domain on that list because that part is managed by another team.

Our apps consume a backend API that provides us that list, and we will update our internal data every time that list is updated.

**Comment by donfuxx** [comment] 2020-11-01 12:20
Ok, I understand. For me theguardian.com seems to work fine though even when it is removed from the whitelist. So it might be possible to remove it from whitelist again

**Comment by cmonfortep** [comment] 2020-11-09 09:32
Thanks, I took a look to the task created when we added that domain into our whitelist, and it seems the site scroll was broken. We will revisit if that's still needed.

However, there's nothing else we can do, and that list gets updated automatically by our privacy team. So we can close this issue. Thanks!

**Closed by cmonfortep** 2020-11-09 09:32 UTC
Labels: bug, needs triage
