### ISSUE TITLE
Partial Protection

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1237] opened 2021-05-16 03:25 UTC
Doesnt Class As Much Of A Bug/Feature

**How to Reproduce**
EFF Testing (Cover Your Tracks) You Get Partial Protections Instead Of Better/Great Protections.

**Expected behavior**
Better Visible Blocking, That The User Should Be Able To Control

![Screenshot_20210516-151912_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/118384517-af57a280-b65a-11eb-8480-fe8239bf3dde.png)

**Fix**
Cookie Disable (1st and Third Party Control), JS Disable, Improved Ad/Tracker Blocking

Let Us Control Our Browsing Experience For Once

**Comment by cmonfortep** [comment] 2021-06-04 09:24
could you provide more info about what trackers were not blocking according to that report? Thanks.

**Comment by cmonfortep** [comment] 2021-06-21 08:50
Closing as not a bug (we don't know which domain is the one not blocked by our app).

For any issue related to not blocking trackers please include more info (as the domain not being blocked). Also, FYI we use the [tracker radar](https://github.com/duckduckgo/tracker-radar) dataset. Feel free to open an issue there if you think any tracker domain should be added to the dataset.

**Closed by cmonfortep** 2021-06-21 08:50 UTC
Labels: bug, needs triage
