### ISSUE TITLE
App Tracking Protection not working with nextdns private dns

### ISSUE THREAD

**Issue by anxiouslelimo** [duckduckgo/Android#2439] opened 2022-10-21 16:03 UTC
App Tracking Protection does not show any apps when nextdns private dns is used. Internet connection seems to be working but dns is routed through nextdns. Tried with nextdns block bypass methods on/off.

**Comment by aitorvs** [comment] 2022-10-21 16:13
Hey @anxiouslelimo, thanks for reporting this. Can you tell us:
* what version of the ddg app you're using?

Also if this understanding is correct:
* you configure nextdns from android private DNS settings
* with nextDns blocking feature ON -> app tracking protection doesn't block any trackers
* with nextDns blocking feature OFF -> app tracking protection (also) doesn't block any trackers

**Comment by anxiouslelimo** [comment] 2022-10-21 17:12
Duckduckgo Version - 5.140.0

1. Right. Configured from android private dns settings.
2. With nextDNS Block Bypass Methods feature (configured through the website) ON/OFF Duckduckgo does not block trackers. Toggled this feature and tested because it can sometimes block other vpn/dns etc.

**Comment by jamorris** [comment] 2022-10-28 17:07
When I enable App Tracking Protection and NextDNS as a private DNS, only the browsers seem to have Internet access. I tried an alternate VPN app that also works internally using a locally stored block list. This also disabled Internet for all apps including browsers, likely because they were not exempt like they are in DDG. Finally, I tried a conventional VPN that uses a web based server. With it and private DNS everything worked. This makes it look like there's a problem with the way internal VPNs and private DNS work. 
DDG version 5.141.0

**Comment by aitorvs** [comment] 2022-10-28 17:22
@jamorris — thanks for reporting this.
Does it happen with other DNS providers, eg. if you configure private DNS with `one.one.one.one` and then disable/enable AppTP to ensure configurations are picked up properly?

**Comment by jamorris** [comment] 2022-10-28 17:39
I tried it with Quad9 as the DNS provider, reenabled DDG's AppTP and it works. I'm guessing the issue is with NextDNS or one of it's settings.

**Comment by Tagby76** [comment] 2022-10-30 21:06
I have tried the same thing with Quad9 and DDG. I had intermittent Internet interruptions with Quad9. Not a lot, just very few. My DDG version is 5.141.0. I don't know if I could reproduce the same problem again.  It's working now, but sometimes I'll have an app that'll freeze because it can't connect to the Internet.

I can definitely confirm it's significantly worse with NextDNS!  Significantly worse!  I can't use my apps at all with NextDNS + DDG's ATP.

**Comment by malmstein** [comment] 2023-06-23 09:52
@anxiouslelimo is this issue still reproducible? Any changes?

**Comment by malmstein** [comment] 2023-06-23 09:53
Closing as duplicate of https://github.com/duckduckgo/Android/issues/2531

**Closed by malmstein** 2023-06-23 09:53 UTC
Labels: Under investigation
