### ISSUE TITLE
login popups redirect to the first tab after login

### ISSUE THREAD

**Issue by gabru-md** [duckduckgo/Android#879] opened 2020-07-02 15:23 UTC
**Describe the bug**
Whenever I lwant to login to a website and the website has one of the other methods like google, GitHub or twitter for login then the browser creates a new tab for me to login. after successful login the tab closes and redirects me to the first tab in my opened tabs list. Even after successful login from the sources the website still asks me to wait for login. everytime I get sent to the first tab instead of the tab that requested that login.

**How to Reproduce**
Make sure there are multiple tabs opened in the browser already.
1. Go to any website that has google, github login etc
2. Click on one if them
3. In the new tab enter the login id and password or whatever is required and wait.
4. It will close the tab and send you to the very first tab in your tabs list 

**Expected behavior**
Should work normally and send me to the website tab with login done.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.57.1
 - Device: One Plus 6
 - OS: Android 10

**Comment by gabru-md** [comment] 2020-07-02 15:41
![ezgif-3-4cd9e0248d39](https://user-images.githubusercontent.com/25414121/86378926-d22dd200-bca7-11ea-82e5-3d0e722dbb6e.gif)

In this gif you can see the bug I'm talking about. In this case the login was successful but the redirect was done to the first tab. sometimes this causes login not to complete.

**Comment by cmonfortep** [comment] 2020-07-03 16:20
Thanks, we have some issues open related to our navigation between tabs and I think this is related to that odd behavior we still need to fix. Like this one https://github.com/duckduckgo/Android/issues/815 (not the same but the root cause could be the culprit).

Thanks for that gif, really love it when people share some visuals here, really helpful. Hope we can fix it soon!

**Comment by gabru-md** [comment] 2020-07-03 16:38
yes, indeed it is one of the navigation issues. Only if I worked on android I'd have tried looking into it but I guess I'd just leave it to you guys to fix it. Also, thanks for the amazing browser, I try to urge people to start using it instead of others. Keep up the good work. 🙌

**Comment by cmonfortep** [comment] 2020-10-16 09:00
We introduced a few improvements in our navigation between tabs. However, I've just tested this scenario again, and the described issue is still there.

It seems we only solved the cases when the tab is closed by the user, **but not when the tab is closed by the site itself.**

**Comment by cmonfortep** [comment] 2021-01-07 16:40
https://app.asana.com/0/0/1199514257586721/f

**Comment by cmonfortep** [comment] 2021-01-14 23:44
Fixed by https://github.com/duckduckgo/Android/pull/1053 

Thanks @tvalle

**Closed by cmonfortep** 2021-01-14 23:44 UTC
Labels: bug, help wanted
