### ISSUE TITLE
Download notifications not displayed

### ISSUE THREAD

**Issue by JeffAment** [duckduckgo/Android#578] opened 2019-08-29 00:24 UTC
**App version:** 5.32.1
**Device model:** OnePlus 5 (hardware device)
**Android version:** Oxygen OS 9.x.x (I didn't think the minor versions were relevant here, but I can find out the exact version if you think otherwise)
**Steps to reproduce:** Initiate a download on a OnePlus 5 running Oxygen OS
**Expected behavior:** Notification appears with download progress and confirms that the download has completed successfully
**Actual behavior:** No notifications appear at all to confirm that a download is in progress, or has been completed

**Notes:**
- The download _does_ complete successfully, but no notifications are displayed.
- This is not my device, nor do I have physical access to it; this complaint comes from a very trusted friend.
- I had my friend test downloads on other apps that I know use `DownloadManager` with the `DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED` flag set.  These apps displayed notifications correctly.
- Perhaps a broadcast receiver and a toast upon completion would remedy this somewhat and serve as a quick "fix" for this issue.
- My friend indicated that she would be happy to test builds that attempt to fix/mask this issue.

**Relevant documentation:** https://developer.android.com/reference/kotlin/android/app/DownloadManager.Request#visibility_visible_notify_completed

**Comment by cmonfortep** [comment] 2021-04-08 09:15
We did some tweaks around the downloads (to better support blobs and data uri) and the download notification. I did some tests and I can't reproduce it anymore so the bug should be fixed.

Going to close this issue. If this happens again, it will be nice to have an example URL, just to investigate if that's happening with a concrete file type. Thanks!

**Closed by cmonfortep** 2021-04-08 09:15 UTC
Labels: bug, needs triage
