### ISSUE TITLE
Issue with RTL

### ISSUE THREAD

**Issue by VitKaspar** [duckduckgo/Android#961] opened 2020-10-07 12:47 UTC
**Describe the bug**
Toolbars look wrong when RTL is on.

Top:
![toolbar2](https://user-images.githubusercontent.com/72492330/95331050-1685cb00-08b2-11eb-949e-c5f964a2e3e1.png)

Bottom:
![toolbar1](https://user-images.githubusercontent.com/72492330/95331031-0f5ebd00-08b2-11eb-83c8-a0b2dce41a4e.png)

**How to Reproduce**
1. Use RTL language or RTL developer mode.
2. Run app and try to open new tab.
3. Look at toolbar.

**Expected behavior**
Mirrored LTR toolbar.

**App version:**
Last app version from Play store.

**Smartphone:**
Samsung galaxy a8+(api 26).
Emulators from Android studio (pixel 2 api 26 & pixel 2 api 29).

**Comment by VMadalin** [comment] 2020-10-07 20:34
Thanks, @VitKaspar for your report I cannot reproduce exactly your behaviour but instead, because in my case the switcher button doesn't appear on RTL, you can check the details on the PR. 

I tested it on Pixel 2 Emulator API 29 with the latest develop version

**Comment by cmonfortep** [comment] 2020-10-07 20:55
Yeah, @VMadalin you are right, I see the same on my device, tab switcher is gone.

Thanks for the report.

**Comment by cmonfortep** [comment] 2020-10-07 20:59
Also found the following issue reviewing our app in RTL mode.

![image](https://user-images.githubusercontent.com/4747865/95387258-c24e0b80-08f0-11eb-99f0-0a8c6c1e7f40.png)

App icon inside settings is not aligned properly.

**Comment by cmonfortep** [comment] 2020-10-11 20:55
Closing this issue, it will fixed in next release by https://github.com/duckduckgo/Android/pull/962

**Closed by cmonfortep** 2020-10-11 20:55 UTC
Labels: bug
