### ISSUE TITLE
bottom search bar

### ISSUE THREAD

**Issue by francescosoave** [duckduckgo/Android#661] opened 2019-12-26 16:55 UTC
Hello, I'd like to suggest a feature, an option in the settings that allows to move the search bar + menu (basically the whole top bar) to the bottom for easier usability.

**Comment by subsymbolic** [comment] 2020-01-31 13:10
This is a big product change and not something we plan to do so I am closing out the issue however we have shared this with our product team as a future idea. Duplicate of #538.

**Closed by subsymbolic** 2020-01-31 13:10 UTC
Labels: duplicate, enhancement
