### ISSUE TITLE
Download Function error!

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1045] opened 2020-12-22 23:33 UTC
**Describe the bug**
When Download A File
They Format Will Always .bin Instead Of apk
(In This Case I Download Apk File Format)

**How to Reproduce**
1. Open DGG 
2. Search And Download APK Fole
3. See The Result Somehow They Format Are .bin

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**
Should Fit Format If The File Format Is APK Then It Should Keep As APK Not Bin File So I Had To Rename The Extension Everytime I Download APK File 

**Smartphone (please complete the following information):**
 - DDG App Version: 5.68.0
 - Device: Realme 5i RMX 2030
 - OS: Android 10 Realme UI

**Comment by cmonfortep** [comment] 2020-12-23 07:56
Thanks, we are aware of this issue. It has the same root cause as for image downloads:  https://github.com/duckduckgo/Android/issues/1018

Closing this as duplicated (same root cause).

**Closed by cmonfortep** 2020-12-23 07:56 UTC
Labels: bug, needs triage

**Comment by NSTAdventure** [comment] 2020-12-23 08:49
Wait! 
I am non root :-( 

@cmonfortep 

Best Regards
NST_Adventure

**Comment by cmonfortep** [comment] 2020-12-23 09:29
I mean that both issues are caused by the same problem.

Files are downloaded as `.bin` when we can't extract the filename and extension from the URL. We will need to move away from the Download Manager in order to extract the correct filename and extension from the header response. The same fix for https://github.com/duckduckgo/Android/issues/1018 will fix this issue.
