### ISSUE TITLE
Picture in Picture support for fullscreen videos

### ISSUE THREAD

**Issue by Mugurell** [duckduckgo/Android#2802] opened 2023-01-31 19:18 UTC
### Describe the issue

The picture in picture feature (https://developer.android.com/develop/ui/views/picture-in-picture) is a staple of other browsers and allow users  to have their media playing as a small overlay over other applications.
Seems to be a limitation of WebView in the scenario of a browser.
Could be left to the users to choose if the app should enter in PiP mode instead of relying on the media status.

### How to Reproduce

- access `youtube.com`
- choose a video to start playing in fullscreen
- switch to another app or go to the device's homescreen.

### Expected behavior

The fullscreen video will continue to play in a small window while users can interact with other applications.

### Environment

```markdown
Happens on all devices and DDG versions.
```

**Comment by cmonfortep** [comment] 2023-02-06 13:44
Not a feature we currently offer. Closing as not a bug report. Thanks.

**Closed by cmonfortep** 2023-02-06 13:44 UTC
