### ISSUE TITLE
Errors when opening results in Firefox (Android 4.4.4)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/android#152] opened 2015-02-09 15:58 UTC
Reported on Duck.co: https://duck.co/forum/thread/12107/android-app-error

**Comment by thm** [comment] 2016-02-17 13:55
Closing this since this is for the previous version of the app on older versions of Android (4.4.4). There are no definite/clear steps to reproduce the issue.

**Closed by thm** 2016-02-17 13:55 UTC
Labels: bug
