### ISSUE TITLE
Won't save checkout information on sweetwater.com on android, works fine on ios

### ISSUE THREAD

**Issue by brandonrains77** [duckduckgo/Android#933] opened 2020-09-13 16:10 UTC
Won't save checkout information on sweetwater.com on android, works fine on ios.

When adding things to cart and then logging in, upon selecting the shipping it get stuck and won't move past that step.  Tested on pixel4xl on ios iphone8 works fine. No idea what to do just did a FDR to fix but nope still won't work

**Comment by brandonrains77** [comment] 2020-09-13 16:18
Also I can't login to amazon even after fireproofing website,, what am I missing here?

**Comment by cmonfortep** [comment] 2020-09-14 09:26
Hi @brandonrains77 I tried to reproduce your issue on my device without success.

I was able to fill in all the forms, and even select the shipping method.

Could you share more info about your device and app version? 

```

**Smartphone (please complete the following information):**
 - DDG App Version: (e.g. 5.25.0) Version can be found:
     - DDG App settings: Settings -> Version
     - System settings: Settings -> Apps & notifications -> App Info
 - Device: [e.g. Pixel 2, Samsung s10]
 - OS: [e.g. Android 10]
 - If applicable, add screenshots to help explain your problem.
```

Thanks

**Comment by brandonrains77** [comment] 2020-09-14 15:16
Thanks for checking, but you are missing one step, after selecting shipping moving on to the next screen it won't save what you selected. Also I am logged into my sweetwater acct. I am on a pixel4xl running android 10 build QQ3A.200805.001, just tested on wife's pixel2 android 9 build pq3a.190801.002 and wouldn't work either
Also I was originally on ddg 5.62.0 and pixel2 is on 5.64.0

**Comment by brandonrains77** [comment] 2020-09-14 16:10
Thanks for checking, but you are missing one step, after selecting shipping moving on to the next screen it won't save what you selected. Also I am logged into my sweetwater acct. I am on a pixel4xl running android 10 build QQ3A.200805.001, just tested on wife's pixel2 android 9 build pq3a.190801.002 and wouldn't work either

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by brandonrains77** [comment] 2020-09-14 16:15
Also I was originally on ddg 5.62.0 and pixel2 is on 5.64.0

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cmonfortep** [comment] 2020-09-30 10:48
Tested again this site and works without issues.

1. Created an account
1. logged into sweetwater.com
1. add an item to cart
1. move to checkout
1. fill in shipping info
1. selected shipping method
1. next
1. payment form (in here I can see previous info is preserved, I was able to fill in billing address using the same info used in previous steps)
1. Review order, ensure all info is preserved

Any other step that I may be missing @brandonrains77 ?

**Comment by brandonrains77** [comment] 2020-09-30 16:02
Thanks for the reply, you followed the steps that I did as well. Still not working for me, I just reset my phone and now have android 11 don't know why it's still not working for me

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cmonfortep** [comment] 2020-10-05 08:06
Sorry @brandonrains77, I will close this issue as I can't reproduce it on my side.

It could be related to some website-specific behavior. I have to say that shipping info was tricky to fill in. I needed to use an address that the website recognized as valid (and confirm it via a validation popup), and then I was able to continue.

**Closed by cmonfortep** 2020-10-05 08:06 UTC
Labels: bug, needs triage
