### ISSUE TITLE
Give the user the ability to choose where to store a file

### ISSUE THREAD

**Issue by Jomme5** [duckduckgo/Android#981] opened 2020-10-27 21:24 UTC
Can't find downloads.

When a file is downloaded, the file is stored somewhere, but I can't find the file location back on the drive. So I lose the file. 

Moto G5 - Android 8.1

Solution: give the user the ability to choose where to store a file. 
The file-system of Android is one big mess in comparison with Windows.

**Comment by cmonfortep** [comment] 2020-10-30 11:14
Hi @Jomme5 
Question: were you trying to download an image? or another type of file? I understand the request for selecting the folder, but I want to know if there's something more going on in our app. For example: we are aware that images sometimes are downloaded as `.bin` files, when that happens they are not visible in gallery/photo apps, so it may be difficult for you to find them there.

**Comment by marksjc** [comment] 2020-11-05 09:15
Also provide access to the downloaded  files directly through UI in menu supra and including "settings"

**Comment by cmonfortep** [comment] 2020-11-09 09:36
Thanks @marksjc, that could be a nice feature to add in the future.

I was asking about what type of downloaded file caused this issue, because in the case of images Android should show them in the default gallery app. However we are aware that some images are downloaded with the wrong extension (`.bin`), and that's causing some issues when trying to find them later. This is important because maybe there's something quick we can do to remove some friction when using our app.

**Comment by marksjc** [comment] 2020-11-21 04:41
Not wanting to create a back & forth here, but having received status that a file downloaded and not finding it in any logical place, I have not executed a search for "*. bin" at the root directory, if that's the feedback you need, I propose you make a specific request. What I've done is moved to a browser (see my question in bookmarks request) that downloads files d with the expected file types in the expected locations. I do appreciate your work and efforts here, but a quick fix in this case sounds like a bit of code that may fix file type, yet the issue is use defined as location, and "some files" as  "bin" communicates very little for anyone to believe you know the scope and depth of the error (which makes any use of downloads break, at least in my experience. The information you need reguarding where the attachments are ending up, with what name and type can't be resolved based on anecdotes, it thorough and rigorous testing on stable devices, in my view. I hope that clarifies what I see as a problem users can test a fix for, perhaps, but not one that can be scoped or identified specifically by any user experience.  If you want more anecdotes to look at you need to specify the conditions you want: attachment size, stored type (at host), error or other messages, where it is NOT found, and where to look for it  (that *.bin search isn't viable).  It's cool to have an apk but users in 2020 have expectations that they have asked for for years with no progress, and the resources dedicated to his product appear very limited communicating a low priority. These are my views as a software product manager, no one else's, but it's important that management understand that your can get people to download an app, but unless it's maintained and improved with transparent progress it reflects poorly on the brand and decreases acceptance/adoption of core offerings.

**Comment by Jomme5** [comment] 2020-11-22 17:11
Don't remember that specific case. But I do download, like in every browser, files from time to time. GPX, JPEG, WAV,... all kinds. On desktop, there is a possibility to specify a download folder or let the browser ask each time were files should be downloaded. It is indeed a problem in some cases files are downloaded with the wrong extension, like you said, specific when images, and then you can't locate or find them on the drive. Maybe integrate some kind of downloadmanager with a list of recent downloads where you can click on, like in every desktop browser.

**Comment by cmonfortep** [comment] 2020-11-23 09:14
Thanks for sharing your views @marksjc, any feedback is appreciated.
Just to clarify something, we are not discarding anything here. I like the proposal of showing a list of your downloaded files and we will propose it to our product team, however, I was just trying to dig a bit into the described issue in case there was something we were missing, and quicker to solve. For example, I've just seen another issue related to downloaded files (https://github.com/duckduckgo/Android/issues/1018), and it looks like images from Twitter are not downloaded with the wrong extension.

@Jomme5 to address your question, files will be stored in different directories depending on their type:
- For images: "Pictures" standard directory.
- For the rest: "Download" standard directory.

The issue here is that the file has the wrong extension (.bin), and even looking into the right folder, apps could not show you that file. So in this case, even if we had a way to select your preferred folder, we will suffer the same issue.

I will create a bug report inside our backlog, and I will post any further update here -> https://github.com/duckduckgo/Android/issues/1018

Let me know if we can close this issue or you have any further questions. Thanks.

**Comment by cmonfortep** [comment] 2021-01-07 16:24
I've created an internal task to keep track of the request of adding a way for users to select where to store each file.
https://app.asana.com/0/0/1199514257586706/f

This should be partially solved once we solve the issue of downloading files with the wrong extension in https://github.com/duckduckgo/Android/issues/1018

**Comment by cmonfortep** [comment] 2021-04-09 10:12
Hello @Jomme5, sorry for the late response.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.

**Closed by cmonfortep** 2021-04-09 10:12 UTC
Labels: Discard, feature request
