### ISSUE TITLE
Performing a search causes the defined values for filter parameters to be set to the default ones

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/Android#4255] opened 2024-03-06 16:18 UTC
### Describe the bug

**v.:** 5.191.0 | Hello. Regardless of the search category among _All_, _Images_, _Videos_, _News_, performing a search **after editing the existing search expression** causes the value of each filter parameter that is located to the right of the _Safe search_ filter parameter to be set to their default one, therefore indicating an issue. That is, only the defined values of the first two filter parameters, _Region_, _Safe search_ are not set to their default ones, which is the intended behavior.

![duckduckgo_android_search_page](https://github.com/duckduckgo/Android/assets/26058215/fe6ae092-3b13-46a6-b1f8-5b4e3509af21)

### How to Reproduce

1. Select a search category among _All_, _Images_, _Videos_, _News_,
2. Set a value for each of those filter parameters that are involved in the issue so that it is no longer the default one.
3. Edit the existing search expression.
4. Perform a search.

### Expected behavior

Performing a search must not cause the defined values for filter parameters to be set to the default ones.

**Comment by CDRussell** [comment] 2024-03-07 10:17
Thanks for the detailed report! 🙏

I think this is largely working as intended and the behavior you observe is consistent across both our Android and iOS apps. When you enter a new search term, we treat that as a brand new search meaning the filters return to their defaults. That said, I definitely understand why that's unexpected or undesirable in a lot of cases.

I'll close this task for now because we won't immediately make any changes to this behaviour, but will discuss it more internally. Thanks for bringing it to our attention.

**Closed by CDRussell** 2024-03-07 10:17 UTC
Labels: bug, needs triage
