### ISSUE TITLE
Unclear state when https connection terminated - Android

### ISSUE THREAD

**Issue by RichardoC** [duckduckgo/Android#963] opened 2020-10-07 21:22 UTC
**Describe the bug**

- Attempt to load any https website with with invalid https (selfsigned /expired cert or cert for wrong domain/etc)
- Nothing happens

This can lead to misleading scenarios as the urlbar will still say that the current URL is the https one. 

This also means there's no warning that you were trying to access a website which then got denied.

**How to Reproduce**

Misleading Scenario:
1. Go to a website with invalid https over http http://eusprig.org/horror-stories.htm or http://neverssl.com
2. Edit url to be https scheme rather than http https://eusprig.org/horror-stories.htm or https://neverssl.com
3. See that the original website is still visible

Visited http, then attempted to visit https which didn't work. http page still rendered but url bar says "https"
![Screenshot_20201007-150500](https://user-images.githubusercontent.com/11242848/95388612-77c99080-08ea-11eb-977b-671f4f70c924.jpg)

Clicking on the privacy report correctly says that the website was http
![Screenshot_20201007-150555](https://user-images.githubusercontent.com/11242848/95388609-76986380-08ea-11eb-8a51-215396366386.jpg)

Lack of a warning that anything's wrong
1. Go to an invalid https website
2. Nothing happens or changes

**Expected behavior**
A warning of some kind to be emitted when the connection was aborted due to invalid https server.
The current screen to be cleared, the previous page shouldn't be rendered while the url is display the new (invalid) page location

**Smartphone (please complete the following information):**
 - DDG App Version: 5.67.0 sc (56700)
 - Device: Oneplus 5
 - OS: Android 9, OxygenOS version 9.0.11

**Comment by cmonfortep** [comment] 2020-10-15 19:48
Thanks for reporting. 

I've been taking a look at the code to understand the issue here.

Turns out that when visiting a site with an invalid certificate after the user has visited a valid site, the WebView loads again the previous site. So in this case, the issue here is that we are not updating correctly the URL.

For the record, we update the URL bar when:
- we detect a new site being loaded
- a site updating the URL (user forwarded or similar)
- from a user input

In this case, the URL bar gets updated by a user input event. Because the site submitted has an invalid certificate, WebView loads again the previous site, we don't detect that as a "new site being loaded", and we don't update properly the URL bar.

Since we are not currently handling invalid certificates, the proper fix for the issue is to detect that the previous page has been loaded again and update the URL bar.

**Comment by cmonfortep** [comment] 2020-10-15 20:01
We are tracing this issue internally: https://app.asana.com/0/414730916066338/1198486065923453/f

**Comment by RichardoC** [comment] 2020-10-16 18:11
Thanks for getting back to me.

That would certainly be an improvement, but I do think there should be some level of warning when a connection is stopped due to invalid certs. What you're proposing would put someone back to the previous page every time, which feels unexpected to me.

**Comment by cmonfortep** [comment] 2020-10-18 07:53
Yes, I do agree with you. We should show some kind of warning if we detect any issue related to an invalid certificate.

> What you're proposing would put someone back to the previous page every time, which feels unexpected to me.

Yes, it was unexpected for me too. I didn't explain it correctly. That's WebView's default behavior. If WebView is moving the user back to the previous site, we should update the URL bar accordingly (at least as a quick fix). But that doesn't mean that we will not work on showing a warning when an invalid certificate is found too.

**Comment by cmonfortep** [comment] 2020-10-18 08:09
I've created another internal task proposing to warn users about invalid certificates: https://app.asana.com/0/414730916066338/1198502707847229/f

**Comment by malmstein** [comment] 2023-06-23 09:49
Closing this stall issue. This doesn’t apply anymore.

**Closed by malmstein** 2023-06-23 09:49 UTC
Labels: bug

**Comment by RichardoC** [comment] 2023-06-23 10:40
The behaviour is still present and occurring with 5.160.0
It can be tested with http://neverssl.com rather than the previously supplied domain above.

**Comment by RichardoC** [comment] 2023-06-23 10:40
Mind reopening @malmstein ?
