### ISSUE TITLE
[Bug] Browser keeps restarting after I close it

### ISSUE THREAD

**Issue by 2011** [duckduckgo/Android#1855] opened 2022-04-11 19:49 UTC
### Describe the bug

I have an older device (Android 6 with just 1 GB of RAM). Applications that continually restart themselves (such as this browser) absolutely cause havoc with this device. If I want to run another app, the device will lock up for several seconds while memory management attempts to close "cached processess" (in Settings / Developer options / Running services). And sometimes, the memory manager will do something I don't want (such as kill the VPN). I always (even a few minutes after killing it) find the DuckDuckGo browser in cached processes consuming 100 MB of RAM. I want to keep that RAM free to improve the performance of the device (and don't tell me it won't - if I disable DuckDuckGo, starting and changing apps becomes much quicker).

### How to Reproduce

Just exit (and force stop) the browser. It eventually starts again.

### Expected behavior

When I leave and stop an app, it should do absolutely nothing until I start it again.

### Environment

```markdown
- DDG App Version: 5.116 (F-Droid)
- Device: Samsung Galaxy Tab 2
- OS: Lineage OS 13.0 (Android 6.0.1)
```

**Comment by cmonfortep** [comment] 2022-04-28 08:09
Hey @2011, we scheduled background work to update data and keep our privacy features updated. I assume when you say the application starts again you are referring to that.
That's the expected behavior, and the Android system will allow background work to run based on available resources, device state, and priorities (that's external to us).

Closing this as it's not a bug.

**Closed by cmonfortep** 2022-04-28 08:09 UTC
Labels: bug, needs triage

**Comment by 2011** [comment] 2022-05-02 18:31
> Closing this as it's not a bug.

On older devices with minimal RAM, this leads to a horrific user experience. I would find a setting to disable this behavior ("don't run in background") **very** useful.
