### ISSUE TITLE
Make search results open in internal browser but external links in external browser by default

### ISSUE THREAD

**Issue by uncertainquark** [duckduckgo/Android#8] opened 2017-05-17 06:36 UTC
Please give an option to open all DuckDuckGo results in Internal browser, but external links in external browser. This is how every search app (Google/Bing/others) does it.

Right now you can either choose internal browser or external. Internal opens everything inside the app and external opens everything (including the searches!) outside the app.

Both options are inconvenient in some way or the other. Please make internal browser the default for DuckDuckGo searches and external browser for external links.

**Comment by gvklive** [comment] 2017-07-16 08:34
I would like to work on this.

**Comment by subsymbolic** [comment] 2017-07-19 19:55
@uncertainquark is this feedback for the currently live search and stories app? I think it makes a lot of sense there.

This repo is for a new prototype app and our plan is to provide an all-round private search and browsing space. In the new app, links will open internally by default however long pressing will provide an option to open externally. That will hopefully feel a lot smoother. Let me know what you think.

**Comment by subsymbolic** [comment] 2017-07-19 20:48
Closing this now as it's a duplicate of https://github.com/duckduckgo/Android/issues/5

**Closed** 2017-07-19 20:47 UTC

**Comment by uncertainquark** [comment] 2017-07-20 03:10
@subsymbolic Yes, the feedback is for the is for the search and stories app and it would very much appreciated to get it working in the suggested way.
