### ISSUE TITLE
Can't answer the survey

### ISSUE THREAD

**Issue by Crowerade** [duckduckgo/Android#1542] opened 2021-11-10 22:27 UTC
When asking for an e-mail to reach me for the follow-up conversation about the duck adress, there isn't any field to fill and i can't go to the next question because no answers has been given.

**Comment by cmonfortep** [comment] 2021-11-11 15:04
Hey @Crowerade, I've asked the team running the survey and they are not aware about any issue there. Actually, we took a look to the responses and everything looks fine.

Sorry that happened to you, maybe it was a temporary survey monkey issue or similar.

Closing this as not a bug in our app, but thanks for sharing the issue with us.

**Closed by cmonfortep** 2021-11-11 15:04 UTC
