### ISSUE TITLE
Add widget to home screen button doesn't work

### ISSUE THREAD

**Issue by Lalisfeed** [duckduckgo/Android#1268] opened 2021-06-03 01:48 UTC
**Describe the bug**
The pop up at the bottom of screen asks to add search widget to home screen. 
On clicking the blue button, it doesn't respond.

**How to Reproduce**
1. Freshly install the app or clear all data (user + cache)
2. Do the first ddg search 
3. Do first url visit on other tab
4. Click fire button and when new tab is open the pop up appears
5. Click on the blue button 'ADD WIDGET'
6. See the button doesn't respond, but the 'DISMISS' button works

**Expected behavior**
It should have added a search widget on the home screen

**Smartphone (please complete the following information):**
 - DDG App Version: 5.87.0
 - Device: Redmi 
 - OS: Android 10
 - Screenshots: 
 
![IMG_20210603_070549](https://user-images.githubusercontent.com/59479762/120573143-bf34fc00-c43a-11eb-89be-67399bde4042.jpg)
![IMG_20210603_065814](https://user-images.githubusercontent.com/59479762/120573150-c0662900-c43a-11eb-8596-30a7d177fa63.jpg)

**Comment by cmonfortep** [comment] 2021-06-04 09:15
We can't reproduce this issue. what happens if you add the widget manually? does that work?

**Comment by Lalisfeed** [comment] 2021-06-04 10:12
manual additon works

**Comment by Lalisfeed** [comment] 2021-06-04 11:30
Check this video, I've recorded the process. Uploading video isn't working so I'm uploading zip file of size 13mb. There is a video in it.
[Duck_Video.zip](https://github.com/duckduckgo/Android/files/6598098/Duck_Video.zip)

**Comment by jayesh-srivastava** [comment] 2021-06-07 08:42
@Lalisfeed Hi, can I work on this issue, if it's still available?

**Comment by Lalisfeed** [comment] 2021-06-07 09:50
> @Lalisfeed Hi, can I work on this issue, if it's still available?

Ask @cmonfortep about this. For now it's still an issue on my phone

**Comment by cmonfortep** [comment] 2021-06-07 09:52
@jayesh-srivastava  can you reproduce it on your device?

**Comment by jayesh-srivastava** [comment] 2021-06-07 09:54
> @jayesh-srivastava can you reproduce it on your device?

Trying to reproduce it in the emulator.

**Comment by jayesh-srivastava** [comment] 2021-06-07 10:22
Hey @cmonfortep I just reproduced it on my emulator.

**Comment by cmonfortep** [comment] 2021-06-07 10:27
Thanks @jayesh-srivastava. Could you briefly explain what's the issue? I wonder why I'm not able to reproduce it on my device.

**Comment by jayesh-srivastava** [comment] 2021-06-07 10:35
Yes sure. You need to add one directory(src) inside the bloom_cpp directory (Android\app\src\main\cpp\third-party\bloom_cpp)  and inside that directory you need to add two files (BloomFilter.cpp and BloomFilter.hpp). The links of these two files are as follows:-
https://github.com/duckduckgo/bloom_cpp/blob/54e581a490236ebc3498e50db37e050cbc61923c/src/BloomFilter.cpp
https://github.com/duckduckgo/bloom_cpp/blob/54e581a490236ebc3498e50db37e050cbc61923c/src/BloomFilter.hpp

I added these two files and the directory, and the application was built in my emulator.

**Comment by jayesh-srivastava** [comment] 2021-06-07 10:36
@cmonfortep (forgot to mention you in the previous comment so doing it here.)

**Comment by cmonfortep** [comment] 2021-06-07 10:54
Thanks, @jayesh-srivastava, `bloom_cpp` seems to be unrelated to the Widget issue.

When using your emulator, do you also have the same problem as @Lalisfeed? if so, have you been able to find the root cause of that issue?

**Comment by jayesh-srivastava** [comment] 2021-06-07 11:10
Hey, @cmonfortep I used the application on my emulator and it's working fine. I used the widget feature and it's working totally fine. The widget was added in the search bar.
For reference I'm adding the screenshot of my emulator:-
![device-2021-06-07-162842](https://user-images.githubusercontent.com/49337716/121006832-fabf2580-c7ae-11eb-9382-8dddc291d8e0.png)

**Comment by Lalisfeed** [comment] 2021-06-07 11:12
You added to from the popup?

**Comment by jayesh-srivastava** [comment] 2021-06-07 11:16
@Lalisfeed yes, inside the application.

**Comment by Lalisfeed** [comment] 2021-06-07 11:22
But I see this not working here (did this for many times but same thing happens). Does the app require special permissions to add widget or it's some issue with my phone. Did you try it on your phone?

**Comment by jayesh-srivastava** [comment] 2021-06-07 11:25
@Lalisfeed Adding the screenshot here for your reference:-
<img src="https://user-images.githubusercontent.com/49337716/121008662-db28fc80-c7b0-11eb-95f8-b5de4d985f99.png" width="300" height="600">


No it did not ask for any special permissions. No haven't tried it on my phone, will do.

**Comment by Lalisfeed** [comment] 2021-06-07 11:26
I did this on phone.

**Comment by jayesh-srivastava** [comment] 2021-06-07 11:43
@Lalisfeed I tested it on the phone itself with app version (5.87.0) and it's working. I used the code cloned from the github repo to test the app on my mobile phone. Maybe you'll have to add the DuckDuckGo widget on your home screen.

**Comment by Lalisfeed** [comment] 2021-06-07 12:05
I tried to do it on other phone. The widget button worked. I think its an issue on my phone.

**Comment by Lalisfeed** [comment] 2021-06-07 12:15
Should I close this issue or leave it open?

**Comment by cmonfortep** [comment] 2021-06-07 14:53
If we can't reproduce it, let's close it. Thanks.

**Closed by cmonfortep** 2021-06-07 14:53 UTC
Labels: bug, needs triage

**Comment by jayesh-srivastava** [comment] 2021-06-07 16:19
Yes @cmonfortep there wasn't an issue as such. Because it worked on my system and phone.

**Comment by Solosmoker** [comment] 2022-07-20 03:53
I can't seem to get to work on Android tablet
