### ISSUE TITLE
Missing dark mode for websites 

### ISSUE THREAD

**Issue by TilloX** [duckduckgo/Android#2685] opened 2022-12-29 14:33 UTC
### Describe the bug

The browser is minimal, privacy friendly and buttery smooth. One of the main reasons I am unable to use it as my default browser is the lack of dark mode in websites. Just like in other browsers, why doesn't duckduckgo have an option to force dark mode in all websites? For the very few websites that supports dark mode, there's a flash of white screen while loading it or going back which is very annoying. Am I missing something or there's some technical reasons behind it? Also, can this feature be implemented in the future?

After researching for someime regarding the issue, I found that the devs are willing to do so but hesitant to force it as it might behave unexpectedly for the websites which doesn't support it. However, dark mode in websites for Duckduckgo is one of the most demanded featue request and there are many people like me who can't use duckduckgo just because of this. Like common guys it's going to be 2023 in less than a week from now and there's still no dark mode support for websites.

The perfect solution according to me would be to give an experimental or labs tab under which users have the option to force dark mode for all websites instead of just closing duckduckgo and searching on chrome/opera or any browser.

### How to Reproduce

1. Open Duckduckgo.
2. Search for anything.
3. Click on the desired website (which doesn't have native dark mode).

### Expected behavior

Users must be given an option to force use dark mode for all websites.

### Environment

```markdown
- DDG App Version:5.145.5
- Device: Samsung Galaxy M12 (Indian variant)
- OS: Android 13
```

**Comment by cmonfortep** [comment] 2023-01-17 16:53
Thanks for the feedback. As you have noticed and we mentioned in https://github.com/duckduckgo/Android/issues/840, we rely on the webview component, and currently, we only support sites that provide a dark mode. 

Closing as not a bug, but we take the feedback, and it's something we could consider if we receive further user feedback. Thanks.

**Closed by cmonfortep** 2023-01-17 16:53 UTC
Labels: bug, needs triage
